### DISCUSSION TITLE
Is it possible to set style of but upon state of entity (not related to button)

### DISCUSSION THREAD

**Discussion by theone11** [jcwillox/lovelace-paper-buttons-row#127] [Q&A]
I have a set of buttons not related to any entity. The buttons only contain name (no icon and no state).

When a button is pressed it sets the value of a input_number entity to a different value.
Is it possible to set the button name (text) color according to the state of the input_number entity's value?

I want the button, which currently coresponds to the input_number value, to be a different color then the other buttons.

For example if "3 hours" button is pressed I want it to change color to RED text (because input_number entity will get value "3") and the other default.

```
- type: custom:paper-buttons-row
  buttons:
    - name: "1 hour"
      tap_action:
        action: call-service
        service: input_number.set_value
        service_data:
          entity_id: input_number.ui_water_boiler_graph_hours
          value: "1"
    - name: "2 hours"
      tap_action:
        action: call-service
        service: input_number.set_value
        service_data:
          entity_id: input_number.ui_water_boiler_graph_hours
          value: "2"
    - name: "3 hours"
      tap_action:
        action: call-service
        service: input_number.set_value
        service_data:
          entity_id: input_number.ui_water_boiler_graph_hours
          value: "3"
    - name: "4 hours"
      tap_action:
        action: call-service
        service: input_number.set_value
        service_data:
          entity_id: input_number.ui_water_boiler_graph_hours
          value: "4"
```
