### DISCUSSION TITLE
How does User-defined Presets works?

### DISCUSSION THREAD

**Discussion by ton6i** [jcwillox/lovelace-paper-buttons-row#133] [Q&A] [answered]
Thanks for the great job you did!!
Every thing i was looking for combined in one.

But somehow i can not manage to get User-defined Presets working.

For testing i use your example:

```yaml
paper_buttons_row:
  presets:
    my_custom_preset:
      ripple: fill
      styles:
        button:
          color: red
views:
  - title: Home
    cards:
      - type: entities
        entities:
          - type: custom:paper-buttons-row
            base_config:
              preset: my_custom_preset
            buttons:
              - entity: light.lamp_keuken
```

I get:
![afbeelding](https://user-images.githubusercontent.com/74511223/236641542-79d0fb75-a84f-42ed-9a1b-4ecd9e142e74.png)

If i copy/past the preset then the color change as expected.
```yaml
views:
  - title: Home
    cards:
      - type: entities
        entities:
          - type: custom:paper-buttons-row
            base_config:
              ripple: fill
              styles:
                button:
                  color: red
            buttons:
              - entity: light.lamp_keuken
 ```

![afbeelding](https://user-images.githubusercontent.com/74511223/236641791-8e499ab7-eedc-4e33-8a9f-d42a75fe43a1.png)

What am i doing wrong?

Please help.
Thanks.
