### DISCUSSION TITLE
Can't define "type: custom:paper-buttons-row" inside of "type: custom:paper-buttons-row"

### DISCUSSION THREAD

**Discussion by ghost** [jcwillox/lovelace-paper-buttons-row#138] [Q&A]
I'm not sure if I can explain this right, but I'm trying to achieve the following:

![1](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/70864968/54fb52a9-7ede-41bc-8484-2b0a4cc06dfa)

but if I do this:

```
      - type: entities
        title: HVAC Fan
        entities: 
          - type: custom:paper-buttons-row
            buttons:
              - entity: switch.hvac_fan
                layout: icon
                styles:
                  button:
                    background-color: rgba(255,255,255,0.1)
                    border-radius: 10px
                    font-size: 25px
                    padding: 50px
                  icon:
                    --mdc-icon-size: 40px
                    color: rgb(142, 142, 147)
                state_styles:
                  "on":
                    button:
                      background-color: "#FFFFFF"
                    icon:
                      color: "#F4B400"
                    name:
                      color: "#727272"
              - type: custom:paper-buttons-row
                buttons:
                  - - icon: mdi:square
                  - - icon: mdi:square
                  - - icon: mdi:square
                  - - icon: mdi:square
```
I get this:

![2](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/70864968/3e398c1b-8be3-40a9-96ab-cb5aea4e8c54)

I can confirm this works though:
```
      - type: entities
        title: HVAC Fan
        entities: 
          - type: custom:paper-buttons-row
            buttons:
              - entity: switch.hvac_fan
                layout: icon
                styles:
                  button:
                    background-color: rgba(255,255,255,0.1)
                    border-radius: 10px
                    font-size: 25px
                    padding: 50px
                  icon:
                    --mdc-icon-size: 40px
                    color: rgb(142, 142, 147)
                state_styles:
                  "on":
                    button:
                      background-color: "#FFFFFF"
                    icon:
                      color: "#F4B400"
                    name:
                      color: "#727272"
              - type: custom:paper-buttons-row
                buttons:
                  - - icon: mdi:square
                  - - icon: mdi:square
                  - - icon: mdi:square
                  - - icon: mdi:square
```
![3](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/70864968/e2fefe76-1868-4346-bc0f-857306fcfd63)

Should I just CSS this?
