### DISCUSSION TITLE
Just color an icon

### DISCUSSION THREAD

**Discussion by saschabrockel** [jcwillox/lovelace-paper-buttons-row#162] [Q&A]
Sorry, I'm not able to color an icon.

I have this one:
```
  - entity: light.kuche_deckenlichter
    extend_paper_buttons_row:
      position: left
      buttons:
        - entity: scene.kuche_kochen
          name: Kochen
          styles:
            '--pbs-button-rgb-color': red
        - entity: scene.kuche_abends
          name: Abend
          icon: mdi:moon-waxing-crescent
```

But it only seems to be possible to assign a preset when the type is this card:
```
  - type: custom:paper-buttons-row
    preset: mushroom
    base_config:
      preset: mushroom
    buttons:
      - entity: scene.kuche_kochen
        name: Kochen
      - entity: scene.kuche_abends
        name: Abend
        icon: mdi:moon-waxing-crescent
```

I just want an icon in red. Not more or less. Because it are scenes and there is no state.

I also love your example ![image](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/33376463/edb56c85-f55b-431d-8bc6-45f04bc78e6c) but I would like to see the code because I don't know how you did this.

The same applies to this:
![image](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/33376463/70ff2415-bee4-42d5-9bf4-e17e22271633)
