### DISCUSSION TITLE
Name out of multiple words in the same row?

### DISCUSSION THREAD

**Discussion by EvaldasD21** [jcwillox/lovelace-paper-buttons-row#205] [Q&A]
Hello,

I could not find a solution what should be a very simple thing. Is it possible to have all the words of "name" in the same row? It seems every space between words sends them to a new row.

```  
type: custom:paper-buttons-row
buttons:
  - layout: icon|name
    name: All Lights
    icon: mdi:lightbulb
    entity: input_boolean.input_toggletest
    tap_action:
      action: toggle
```

![image](https://github.com/user-attachments/assets/61977e1b-cd6c-43bd-b845-872ffc6dc921)
