### DISCUSSION TITLE
Possible to evenly space multiple buttons to each other?

### DISCUSSION THREAD

**Discussion by alexrmay91** [jcwillox/lovelace-paper-buttons-row#53] [Q&A] [answered]
I have a few few buttons of varying widths, so they don't appear centered overall.

![image](https://user-images.githubusercontent.com/67204669/126913022-fa33979c-acff-4cd4-8b07-829d722b2d8e.png)

Here's an example of a card along with the same card broken into a horizontal stack. You can see the plain paper-buttons card isn't evenly spaced/centered. Downsides of using a horizontal stack are the borders as well as the fact that `base_config` can't be used.

Let me know if I'm missing a way to do this, but some sort of "button spacing" option would be great to have.

Here's the config for the top card:

```
type: entities
entities:
  - type: custom:paper-buttons-row
    base_config:
      style:
        name:
          color: white
          font-size: 16px
        state:
          font-size: 10px
    buttons:
      - entity: binary_sensor.bedroom_door_contact
        layout: name_icon_state
        name: Bedroom Door
        state_icons:
          'off': mdi:door
          'on': mdi:door-open
        state_text:
          'off': Closed
          'on': Open
      - entity: binary_sensor.garage_door_contact
        layout: name_icon_state
        name: Garage Door
        state_icons:
          'off': mdi:garage-variant
          'on': mdi:garage-open-variant
        state_text:
          'off': Closed
          'on': Open
      - entity: input_boolean.bedroom_occupied
        layout: name_icon_state
        name: Bedroom
        tap_action:
          action: more-info
        state_icons:
          'off': mdi:account-outline
          'on': mdi:account-alert
        state_text:
          'off': Empty
          'on': Occupied
```

**Comment by jcwillox** [comment, marked as answer]
Good question, so the best way to do this is by using `width: 100%` and `margin`, basically, you set each button to have a width of 100% and then use margins to control the spacing between them. Here's an example
```yaml
type: entities
title: Internet
state_color: true
entities:
  - type: custom:paper-buttons-row
    base_config:
      style:
        button:
          margin-bottom: 8px
          margin-left: 4px
          margin-right: 4px
          width: 100%

          # other aesthetic styling options
          background-color: var(--table-row-background-color)
          border: 1px solid
          border-color: '#FFFFFF'
          border-radius: 4px
          justify-content: center
    buttons:
      - icon: mdi:router-wireless
        name: ROUTER
        tap_action:
          action: call-service
          service: shell_command.reboot_router
      - icon: mdi:lan
        name: WAN
        tap_action:
          action: call-service
          service: shell_command.restart_wan
      - icon: mdi:wifi
        name: WLAN
        tap_action:
          action: call-service
          service: shell_command.restart_wlan
```

**Comment by Mithrox** [comment]
I have a follow-up question around this topic. I have a "box" with 21 paper buttons, where I have 3 on each row. When I did set this up, I defined style and state_style on each single button, and it's a pita to change. So this is a great way of doing it much easier. However, I have one issue now when I did it on top. This is my code (for some reason, when I use insert code with the option, it just shows as a table, so this was the easiest way to show it with formatting):

![image](https://user-images.githubusercontent.com/58890682/150780486-6e3cc2ed-89cf-4e65-a667-542e8a17f6bf.png)

It now shows the buttons correctly and evenly spaced, and it takes the "global" config when it comes to spacing, radius etc. However, I did have a state_styles to keep the name white instead of the normal blue, and no matter how I add it to the base_config, it does not seem to stick. It's not in the code over as I couldn't get it to work, but the second row here is how I would like to have it look, while the first row is how it does look when it's not defined in base_config anywhere.

![image](https://user-images.githubusercontent.com/58890682/150780754-8eaaa180-05b4-4de1-8f4b-1ad0f86bf436.png)

Now the last question is this, I use as vertical stack and then putting 21 paper buttons in it, and it means for every 3rd button, I have to defined a new -type: custom:paper-buttons-row. When I do, the base_config just works for the first (which makes sense). Is there a way to make this easier, or is there a way to drop vertical stack and do several lines of paper-buttons instead?

Sorry if this should be obvious, it's a learning process :)

**Reply by jcwillox** [reply]
Yes, you actually can specify multiple rows of buttons in a single config, check out the second example in this section [lovelace-paper-buttons-row#multiple-rows-of-buttons](https://github.com/jcwillox/lovelace-paper-buttons-row#multiple-rows-of-buttons). You might also be able to save a couple lines by adding parts of `tap_action` and `hold_action` to `base_config`.

**Reply by Mithrox** [reply]
Sorry for being the stupid person here, but are you referring to the bottom example, this one?

![image](https://user-images.githubusercontent.com/58890682/150794191-3c4ef734-faa7-40b6-8c55-9071274de129.png)

If so, I am struggling a bit to understand the structure of the how to add the buttons for second/third etc row.

And about the tap_action and hold_action, that would be awesome as expecially hold action is more_info for everyone. Can I just basically add the hold_action: and then the action: below it under base_config?

**Reply by jcwillox** [reply]
All good, so the `- -` is how you declare a nested list in YAML, so its a list of lists, the outer list is the list of rows, and each row has a list of columns so to you can add an extra row or column like this.

```yaml
type: entities
entities:
  - type: "custom:paper-buttons-row"
    buttons:
      # row 1
      - - entity: light.bedroom_underglow  # column 1
        - entity: light.bedroom_underglow  # column 2
          name: Light
          icon: mdi:lightbulb
        - entity: light.bedroom_underglow  # column 3

      # row 2
      - - entity: light.bedroom_light  # column 1
        - entity: light.bedroom_underglow  # column 2
          icon: "mdi:lightbulb"  # column 3

      # row 3
      - - entity: light.bedroom_underglow  # column 1
        - entity: light.bedroom_underglow  # column 2
        - entity: light.bedroom_underglow  # column 3
```

Hopefully, that's a bit clearer, let me know how it goes.

> And about the tap_action and hold_action, that would be awesome as expecially hold action is more_info for everyone. Can I just basically add the hold_action: and then the action: below it under base_config?

Yes, exactly

```yaml
base_config:
  styles:
    # ...
  tap_action:
    action: call-service
    service: light.toggle
  hold_action:
    action: more-info
buttons:
  entity: light.light
  tap_action:
    service_data:
      entity_id: light.light
```
