### DISCUSSION TITLE
Is it possible to turn stop displaying buttons entirely based on state?

### DISCUSSION THREAD

**Discussion by maxshcherbina** [jcwillox/lovelace-paper-buttons-row#65] [Q&A] [answered]
I recently discovered this card and I must say it is fantastic!
One use case that I thought of was to create [chips](https://material.io/components/chips) that I can display at the top of my UI. Given this, I would love it for a button to appear/disappear depending on the state of an entity. I'd like for the next button in the row to take its place. Is this currently possible?

My chips:
![image](https://user-images.githubusercontent.com/17325179/143933399-115033c7-2bd6-4871-9649-0777f5bccfa6.png)

**Comment by jcwillox** [comment, marked as answer]
Yep, should be pretty easy with `state_styles` or by [templating](https://github.com/jcwillox/lovelace-paper-buttons-row#templating) the `display` css property.

```yaml
- type: custom:paper-buttons-row
  buttons:
    - entity: light.bedroom_light
      state_styles:
        'off':
          button:
            display: none
```
or with Jinja templates
```yaml
- type: custom:paper-buttons-row
  buttons:
    - entity: light.bedroom_light
      style:
        button:
          background: black
          display: "{{ is_state(config.entity, 'off') and 'none' }}"
          # display: "{{ is_state('light.bedroom_light', 'off') and 'none' }}"
```

**Comment by maxshcherbina** [comment]
Wow Thanks - that is perfect & pretty easy! This is a fantastic piece of work.  

I was also wondering if you could recommend a method to make these buttons further dynamic:

1. I would ideally like them to be scrollable (ie you could use your finger to grab and scroll through them - but I think I can probably achieve that with other cards in conjunction with this one) 

2. I was also looking at saving space - if there are too many cards showing it would remove the state and leave just the icon (dynamically). I understand you can do this: 

```yaml
    state_styles:
      disarmed:
        state:
          display: none
```
Or even use a jinja template to display the state if certain conditions are met, (as you've shown above) but it would be great if I could add +1 to a variable each time a button is displayed - and when that number reaches 4 for instance, the state text disappears and youre left with just the icon.

Thanks for your help though, this is already quite an awesome addition to my dashboard!
