### DISCUSSION TITLE
Icon size

### DISCUSSION THREAD

**Discussion by chma31** [jcwillox/lovelace-paper-buttons-row#71] [Q&A] [answered]
Hello,

first of all : good job ! It really helps and fits with what I was looking for.
A short question : is there a way in this version to change the size of the icon (increase it) ? I wasn't able to find a way (yet).
That would be perfect to add it when it's not yet possible.

Regards.

**Comment by jcwillox** [comment, marked as answer]
Yep there is, using CSS styles
```yaml
type: custom:paper-buttons-row
buttons:
  - entity: light.monitor_leds
    style:
      button:
        font-size: 2.2rem
      icon:
        '--mdc-icon-size': 100px
```
