### DISCUSSION TITLE
Using last_changed value in button name but it doesn't update

### DISCUSSION THREAD

**Discussion by MattPuffin** [jcwillox/lovelace-paper-buttons-row#98] [Q&A]
Hi all,

Disclaimer: While I'm not new to HA, I am new to going much deeper than just accepting what HA shows me with the default cards. So apologies if I am going about this completely wrong!

paper-buttons-row has blown my mind in terms of how much better it has made my lovelace views look, but it's sent me down a rabbit hole for perfection which maybe isn't the best :)

I set up a row to show my back door sensor and a temperature sensor for the room, but I wanted the door sensor to say how long it had been since the state last changed (I used to have a history graph showing the door sensor but it was awful)

This is what I have set up:

![image](https://user-images.githubusercontent.com/43544578/181909255-561ec35a-c4a4-4348-8c3c-7b4292039e3b.png)

And this is the code:

```yaml
  - type: custom:paper-buttons-row
    base_config:
      layout: icon_name
      state_styles:
        'on':
          button:
            color: white
        'off':
          button:
            color: gray
          icon:
            color: rgb(50,50,50)
      state_icons:
        'on': mdi:door-open
        'off': mdi:door-closed
    buttons:
      - entity: binary_sensor.door_sensor_contact
        name: ' Back Door {{ relative_time( states.binary_sensor.door_sensor_contact.last_changed) }} ago'
      - entity: sensor.kitchen_motion_sensor_temperature
        name: '{{ states(''sensor.kitchen_motion_sensor_temperature'') }} °C'
        style:
          button:
            color: white
```

The issue it that when the state of the door changes, the button updates to say 0 seconds ago, but it will stay saying that until the browser is refreshed etc. Is there a way to force it to update every x seconds for example?

I would also love it if I could force the x minutes ago to be on a new line so the button would read:

Back Door
3 minutes ago

But that's much more trivial, if I can just get it working I'll be happy!
