### ISSUE TITLE
fixed span for buttons on different text length

### ISSUE THREAD

**Issue by thehiddenbit** [jcwillox/lovelace-paper-buttons-row#10]
Is there any way to get around that shifted buttons on different text length? I already tried alignments global and per button (Text left, buttons right), but without success.

![2020-05-17 16_31_23-Übersicht - Home Assistant - Brave](https://user-images.githubusercontent.com/8467262/82151604-8a203080-985c-11ea-8ac0-1809a3ebb1fe.png)

**Comment by jcwillox** [comment]
That's a cool application for the align-right option. I can't be 100% sure without seeing your config but the below style should work (use this for the first button).

```yaml
align_icon: right
style:
  button:
    width: 100%  # makes button take as much space as available, pushes buttons to the right
  text:
    flex-grow: 1  # text will use a much space as available, will push icon to the right
    text-align: left  # text is default centered
```
