### ISSUE TITLE
[FR]: Background color

### ISSUE THREAD

**Issue by NickyMB** [jcwillox/lovelace-paper-buttons-row#103]
### Is your feature request related to a problem? Please describe.

Im missing way to change background for whole row. 

### Describe the solution you'd like

There should be something like background-row-color to change it

### Describe alternatives you've considered

No idea

### Additional context

There's difference between in bg color in normal row and in paper row
![image](https://user-images.githubusercontent.com/82083134/191077237-7bf0c891-9fb4-4aa1-a7ec-2cdd9a1a60d6.png)

**Comment by jcwillox** [comment]
Yep this is already possible via the `styles` or `extra_styles` options, here's a simple example.
```yaml
type: entities
entities:
  - type: custom:paper-buttons-row
    styles:
      background: red
```

Feel free to re-open this if that's not what you were looking for.
