### ISSUE TITLE
Button color based on numeric state value

### ISSUE THREAD

**Issue by homonto** [jcwillox/lovelace-paper-buttons-row#104]
I am ok with state_styles when it comes to "on" "off" etc - it is quite simple i.e. such code:
```
type: entities
entities:
  - type: custom:paper-buttons-row
    buttons:
      - entity: binary_sensor.printers_thermostat_battery_low
        layout: state
        tap_action:
          action: navigate
          navigation_path: /lovelace/trv4
        style:
          button:
            color: white
            width: 30px
            height: 5px
            font-size: 12px
            border-radius: 1px
            padding: 6px
        state_styles:
          'off':
            button:
              color: grey
          'on':
            button:
              color: red
          unknown:
            button:
              color: yellow
        state_text:
          'off': OK
          'on': LOW
          unknown: N/A
show_header_toggle: false
```
gives me: OK in grey as the state is "off"
<img width="96" alt="Screenshot 2022-10-20 at 12 45 57" src="https://user-images.githubusercontent.com/46562447/196940075-537b9fb5-e234-469a-9933-9edf3fcba333.png">

But now I would like to have another one that changes the color based on the value of the status, i.e.
green when state is > 4
yellow when > 3.7 and < 4
red when < 3.7

But I am struggling with template there.
This one does not work:
```
type: entities
entities:
  - type: custom:paper-buttons-row
    buttons:
      - entity: sensor.esp32026_battery
        layout: state
        style:
          button:
            color: grey
        state_styles:
          button:
            color: |-
              {% if states('sensor.esp32026_battery') | float > 4.0 %}
                green
              {% else %}
                yellow
              {% endif %} 
show_header_toggle: false
```

It shows grey (as in general state) rather than green )as in state_styles)
<img width="121" alt="Screenshot 2022-10-20 at 12 51 49" src="https://user-images.githubusercontent.com/46562447/196941114-3defd983-291e-4161-b621-005d61270592.png">

What am I doing wrong here?

**Comment by uli-rpi** [comment]
Try this:

```
type: custom:paper-buttons-row
buttons:
  - entity: sensor.sz_fenster_battery_percent
    layout: state
    tap_action:
      action: more-info
    name: |
      {{ states('sensor.sz_fenster_battery_percent')}}     state_styles:
    styles:
      button:
        border-radius: 8px
        width: 72px
        height: 72px
        background-color: deepskyblue
        color: |-
          {% if states('sensor.sz_fenster_battery_percent') | float < 30 %}
            red
          {% else %}
            black
          {% endif %}  
```

![grafik](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/84666727/9776a2bc-2d53-4f50-b1f7-898b895cef3a)
