### ISSUE TITLE
Card empty when state-styles defined & Group Helper used as button

### ISSUE THREAD

**Issue by Masterz69** [jcwillox/lovelace-paper-buttons-row#107]
### The problem

In following case entire card "disapperas" aka shown empty. No records in HA log.

### What version of Paper Buttons Row has the issue?

1.0.1

### What version of Home Assistant are you running?

2022.11.1

### What version of the Frontend are you running?

20221102.1

### Example YAML snippet

```yml
- type: entities
            title: OverHang
            show_header_toggle: false
            state_color: true
            entities:
              - type: custom:paper-buttons-row
                base_config:
                  icon: mdi:ceiling-light-outline
                  styles:
                    name:
                      color: var(--primary-text-color)
                  state_styles:
                    "unavailable":
                      icon:
                        color: var(--state-icon-error-color)
                buttons:
                  - - entity: switch.overhang_lights_entry
                      icon: mdi:ceiling-light-multiple-outline
                      name: Entry by
                      tap_action:
                        action: more-info
                    - entity: switch.light_overhang_entry_switch
                      icon: mdi:toggle-switch-variant-off
                      layout: state|icon|name
                      name: Switch
                      state: (
                      tap_action:
                        action: more-info
                    - entity: switch.light_overhang_entry_motion
                      icon: mdi:motion-sensor
                      name: Motion
                      tap_action:
                        action: more-info
                    - entity: switch.light_overhang_entry
                      icon: mdi:home-automation
                      layout: icon|name|state
                      name: HA/RF
                      state: )
```

### Additional information

![image](https://user-images.githubusercontent.com/15225823/205448310-7c52b04c-54f8-498e-82e1-83d22badcc03.png)

```entity: switch.overhang_lights_entry``` - Group Helper (as switch).

As soon ```entity: switch.overhang_lights_entry``` removed from config or changed to regular entity - all works fine.
