### ISSUE TITLE
How to get presets working?

### ISSUE THREAD

**Issue by gvssr** [jcwillox/lovelace-paper-buttons-row#109]
### The problem

Trying to get the new preset function to work by following the docs, but they don't seem to be applying

### What version of Paper Buttons Row has the issue?

2.0.0

### What version of Home Assistant are you running?

2022.12.1

### What version of the Frontend are you running?

20221208.0

### Example YAML snippet

At the top of my raw config:

```yml
paper_buttons_row:
  presets:
    my_custom_preset:
      ripple: fill
      styles:
        button:
          color: red
views:
```

and then on a buttons row:

```yml
  - type: custom:paper-buttons-row
    buttons:
      - entity: sensor.home_temperature_average
        name: Climate
        icon: mdi:thermometer
        preset: my_custom_preset
```
