### ISSUE TITLE
How to achieve glow effect?

### ISSUE THREAD

**Issue by macbih** [jcwillox/lovelace-paper-buttons-row#110]
I am trying to implement a glow effect which perfectly works with the _Button Card_ (source see [here](https://community.home-assistant.io/t/lovelace-button-card/65981/5879)).

```
# Button Card syntax
state:
  - value: 'on'
    styles:
      card:
        - '-webkit-box-shadow': 0 0 0.95rem 0.2rem var(--button-card-light-color)
        - box-shadow: 0 0 0.95rem 0.2rem var(--button-card-light-color)
        - transition: all 2s ease
```

So far, I was not able to transfer it to the _Paper Buttons Row_ to achieve the same glow effect. For example, this `base_config` **does not work**:

```
    base_config:
      preset: mushroom
      state_styles:
        'on':
          button:
            '-webkit-box-shadow': 0 0 0.95rem 0.2rem var(--button-card-light-color)
            box-shadow: 0 0 0.95rem 0.2rem var(--button-card-light-color)
            transition: all 2s ease
```

Can someone help me with this, please?

**Comment by jcwillox** [comment]
the css variable `--button-card-light-color` is only available when using button-card, so you need to use the equivalent of paper-buttons which is `rgb(var(--pbs-button-rgb-state-color))` or `rgb(var(--pbs-button-rgb-active-color))`

```yaml
    base_config:
      preset: mushroom
      state_styles:
        'on':
          button:
            '-webkit-box-shadow': 0 0 0.95rem 0.2rem rgb(var(--pbs-button-rgb-state-color))
            box-shadow: 0 0 0.95rem 0.2rem rgb(var(--pbs-button-rgb-state-color))
            transition: all 2s ease
```

**Comment by macbih** [comment]
Thank you very much, Josh @jcwillox! That works perfectly! And also thanks for the CSS explanation!

Can you please add a short example how to implement this as a preset for the raw configuration editor? Unfortunately, I am not able to get this working as well (while other presets for the button card do work).
```
paper_buttons_row:

  presets:

    lampe:
      preset: mushroom
      ???
```

Just putting the `state_styles` section into there does not seem to bee sufficient. Thank you!
