### ISSUE TITLE
Version 2.0.1 does no longer show states

### ISSUE THREAD

**Issue by TobiasSchwarz74** [jcwillox/lovelace-paper-buttons-row#114]
### The problem

I'm using name_state and icon_state a lot, but after updating from 2.0.0 to 2.0.1, states are no longer shown in my UI.

### What version of Paper Buttons Row has the issue?

2.0.1

### What version of Home Assistant are you running?

2023.2.3

### What version of the Frontend are you running?

 20230202.0 - latest

**Comment by 03397** [comment]
I have the exact same issue. Same applies to version 2.1.0

``
type: entities
entities:
  - type: custom:paper-buttons-row
    styles:
      '--pbs-button-color': white
    buttons:
      - entity: sensor.upstairs_temperature
        layout: icon_name_state
        name:
          attribute: friendly_name
        state:
          case: first
      - entity: sensor.downstairs_temperature
        layout: icon_name_state
        name:
          attribute: friendly_name
        state:
          case: first
      - entity: sensor.hot_water_temperature
        layout: icon_name_state
        name:
          attribute: friendly_name
        state:
          case: first
state_color: false
``

**Comment by jcwillox** [comment]
Yep clearly I need a more organised set of test buttons, this never should've got into production. But it should at least be fixed with https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/2.1.1 👍, do let me know if you find any other regressions.

**Comment by 03397** [comment]
Problem fixed in version  2.1.1

**Comment by luixal** [comment]
I think I'm just hitting this bug in current version.

This is how I'm using it:

```yaml
- type: custom:paper-buttons-row
    buttons:
      - entity: switch.bosch_drc96aq..._setting_lighting # shortened
        layout: icon
        icon: mdi:track-light
        styles:
          '--pbs-button-rgb-color': red
          '--pbs-button-rgb-active-color': green
```

also tried:

```yaml
- type: custom:paper-buttons-row
    styles:
      '--pbs-button-rgb-color': red
      '--pbs-button-rgb-active-color': green
    buttons:
      - entity: switch.bosch_drc96aq..._setting_lighting  # shortened
        layout: icon
        icon: mdi:track-light
```

No effect at all. Any ideas?

Thanks!
