### ISSUE TITLE
Styles not inheriting from presets on HA 2023.04

### ISSUE THREAD

**Issue by danm1989** [jcwillox/lovelace-paper-buttons-row#123]
### The problem

After updating to HA 2023.04, it appears to have broken the PBR plugin.

The preset styles are not adopted when called on later in ui-lovelace.yaml.   This problem can be resolved by using card-mod to style the buttons as a work around.

Note: the issue is with the buttons on the bottom of my entertainment card (HDMI Source)  they should be rounded icons like the LG icon under the 'TV' section but are instead square.  The LG button is actually an image overlaid on the button, so appears normal.

![image](https://user-images.githubusercontent.com/121988175/230149768-9b3690d1-a688-4b76-aaa2-9b86414a3754.png)

 

### What version of Paper Buttons Row has the issue?

2.1.2

### What version of Home Assistant are you running?

HA 2023.04.0

### What version of the Frontend are you running?

20230405.0

### Example YAML snippet

```yml
### Comment: Paper Button Presets defined before views: in yaml mode. ####
paper_buttons_row:
  presets:
    entertainment:
      ripple: none
      tooltip: false
      styles:
        button:
          border-radius: 100%
          height: 36px
          width: 36px
        icon:
          --mdc-icon-size: 34px


##### Comment: Calling the button preset later on in the view #####

          - type: section
            label: "HDMI Source"
            style: |
              .label {
                pointer-events: none;
              }
          - type: custom:paper-buttons-row
            preset: entertainment
            buttons:
              - icon: phu:apple-tv
                styles:
                  button:
                    background-color: '#FFFFFF'
                  icon:
                    color: black
                tap_action:
                  action: call-service
                  service: input_number.set_value
                  service_data:
                    entity_id: input_number.hdmi_input
                    value: 0
```

### Additional information

![image](https://user-images.githubusercontent.com/121988175/230150926-ca85347c-ae17-4998-b1ca-2a6d50d8483e.png)

The console information seems to suggest the plugin loaded fine without issue.

This issue isn't present on HA 2023.03 and has only appeared as a result of the 2023.04 HA update.

**Comment by Otiel** [comment]
Same issue here, using the `preset` in `extend_paper_buttons_row`:

```
title: Home
paper_buttons_row:
  presets:
    shutter_to_sun_position_preset:
      tooltip: Open cover to sun position
      icon: mdi:weather-sunset-down
      styles:
        button:
          color: var(--primary-text-color)
          margin-right: 8px
views:
  - path: shutters
    icon: mdi:window-shutter
    title: Shutters
    badges: []
    cards:
      - type: entities
        title: First floor
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
            label: Living room
          - entity: cover.shutter_kitchen
            secondary_info: position
            name: Kitchen
            extend_paper_buttons_row:
              extra_styles: |
                paper-button:hover {
                  background-color: #242424;
                }
              preset: shutter_to_sun_position_preset
              buttons:
                - tap_action:
                    action: call-service
                    service: script.open_kitchen_shutter_to_sun_position
```

Affected version:

```
Home Assistant 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest
Paper Buttons Row 2.1.2
```

I had no issue with Home Assistant 2023.3.
