### ISSUE TITLE
paper-buttons-row-action-handler causing body overflow

### ISSUE THREAD

**Issue by rafma0** [jcwillox/lovelace-paper-buttons-row#125]
### The problem

Hi, I just added your component to my view and it seems like `paper-buttons-row-action-handler` with `position: absolute` is causing an overflow in the `body`.

![image](https://user-images.githubusercontent.com/28578847/231486899-0d3749a9-e33c-453d-b3d4-7c3a3585f9b7.png)

Can you please check? thank you

### What version of Paper Buttons Row has the issue?

2.1.3

### What version of Home Assistant are you running?

2023.4.2

### What version of the Frontend are you running?

20230406.1

### Additional information

I also tried having only a single button in a new view, with

```yml
type: entities
entities:
  - type: custom:paper-buttons-row
    buttons:
      - icon: mdi:power
```
and the behavior is the same
