### ISSUE TITLE
Presets again broken with Home Assistant 2023.4.6?

### ISSUE THREAD

**Issue by TobiasSchwarz74** [jcwillox/lovelace-paper-buttons-row#128]
### The problem

I tried to use the presets as defined in the documentation, but they are not working.
Only "mushroom" works, but no own preset templates.

Maybe again broken with Home Assistant 2023.4.6?

### What version of Paper Buttons Row has the issue?

2.1.3

### What version of Home Assistant are you running?

Home Assistant 2023.4.6

### What version of the Frontend are you running?

Frontend 20230411.1 - latest

### Example YAML snippet

```yml
see docs
```

**Comment by ton6i** [comment]
I had the same and it will work after refresh the browser.


My preset:

paper_buttons_row:
  presets:
    main_button:
      styles:
        name:
          color: var(--primary-text-color)
          font-size: 15px
          margin-left: 15px
        button:
          width: 100%
          margin-left: 0%
          justify-content: flex-start
      state_styles:
        'on':
          icon:
            color: var(--state-active-color)
        'true':
          icon:
            color: var(--state-active-color)
    state_button:
      styles:
        button:
          height: 20px
          width: 20px
          margin-top: 3%
          margin-left: 3%
          margin-right: 0%
          border: 0px solid
          border-radius: 17px
        name:
          color: var(--secondary-text-color)
          font-size: 10px
        state:
          color: var(--primary-text-color)
          font-size: 16px
      state_styles:
        'on':
          icon:
            color: var(--state-active-color)
        'true':
          icon:
            color: var(--state-active-color)

My control:
  - type: custom:paper-buttons-row
    buttons:
      - entity: light.lamp_hal_links
        preset: main_button
        name: hal
        layout: icon|name
        tap_action:
          action: call-service
          service: light.toggle
          service_data:
            entity_id: light.lamp_hal_links, light.lamp_hal_rechts
      - entity: light.lamp_hal_links
        preset: state_button
        layout: icon
      - entity: light.lamp_hal_rechts
        preset: state_button
        layout: icon

**Comment by TobiasSchwarz74** [comment]
```
 -paper_buttons_row:
  presets:
    scene_button:
      base_config:
        layout: icon_name
      styles:
        justify-content: flex-end
        button:
          min-width: 50px
          margin-top: '-10px'
          margin-bottom: '-10px'
        name:
          font-size: 80%
          margin-top: '-5px'
          color: var(--primary-text-color)
...
      - type: custom:paper-buttons-row
        preset: scene_button
        buttons:
```
doesn't work for `layout` and `justify-content`.

Have to write
```
      - type: custom:paper-buttons-row
        styles:
          justify-content: flex-end
        base_config:
          layout: icon_name
        preset: scene_button
        buttons:
```
