### ISSUE TITLE
Entity and config.entity not working as expected

### ISSUE THREAD

**Issue by luixal** [jcwillox/lovelace-paper-buttons-row#132]
### The problem

When using jinja templates and according to the docs, `entity` variable should be used rather than `config.entity`. As seen in the [Jinja Templates section in the docs](https://github.com/jcwillox/lovelace-paper-buttons-row#jinja-templates):

```
entity - the entity_id from the current entity row configuration. **This must be used instead of config.entity for the template to automatically update**.
```

This actually works, but doesn't update on attribute's changes:

```yaml
  - type: custom:paper-buttons-row
    buttons:
      - entity: light.main_room
        layout: icon_name
        name: "{{ state_attr(config.entity, 'duration') }}: "
        state: "{{ states(config.entity) | title }}"
```

but this doesn't (entity's name is shown):

```yaml
  - type: custom:paper-buttons-row
    buttons:
      - entity: light.main_room
        layout: icon_name
        name: "{{ state_attr(entity, 'duration') }}: "
        state: "{{ states(config.entity) | title }}"
```

BTW: It would be great to be able to use javascript templates :)

### What version of Paper Buttons Row has the issue?

21
