### ISSUE TITLE
[FR]: Add state_actions that works like state_styles, state_icons and state_text

### ISSUE THREAD

**Issue by luixal** [jcwillox/lovelace-paper-buttons-row#135]
### Is your feature request related to a problem? Please describe.

I'm trying to buildd a row of buttons for an irrigation system. One of this buttons is a toggle (play/stop) button. I can make the button show a different icon and style according to state (playing/stopped), but I need to make a different service call according to the state:

Start irrigation:

```yaml
action: call-service
service: irrigation_unlimited.manual_run
service_data:
  entity_id: binary_sensor.irrigation_unlimited_c1_z1
  time: 00:01:00 #<--- I don't need this param for pausing
```

Stop irrigation:

```yaml
action: call-service
service: irrigation_unlimited.cancel
service_data:
  entity_id: binary_sensor.irrigation_unlimited_c1_z1
```

If I use templates (i.e: putting this card inside a `button-card` card) I get an error when stopping irrigation because of the extra `time` field.

### Describe the solution you'd like

For my use case, if a value of `none` makes the `time` params not being sent in the service call would work for me.

I think a better solution would be to follow the style of `state_styles`, `state_icons` and `state_text` by providing an `state_actions` that allows you to perform different actions according to the state of the entity.

### Describe alternatives you've considered

Putting this card inside a `button-card` to template the `service_data` param, but I haven't been able to return a dict that is taken by this card.

Using lovelace-gen seem too much for me just for this card.
