### ISSUE TITLE
Service Call not provided

### ISSUE THREAD

**Issue by pedolsky** [jcwillox/lovelace-paper-buttons-row#139]
### The problem

I can’t call `media_player.play_media ` service: 
_Required key not provided @ data['media_content_id']_
The service is working in default button card. Am I missing something.?

My card config:

```

type: entities 
entities:
  - type: custom:paper-buttons-row
    buttons:
      - icon: mdi:ab-testing
        tap_action:
          action: call-service
          service: media_player.play_media
          target:
            entity_id: media_player.echo_show
          data:
            media_content_id: stop
            media_content_type: custom

```

### What version of Paper Buttons Row has the issue?

2.1.3

### What version of Home Assistant are you running?

Home Assistant 2023.6.1

### What version of the Frontend are you running?

Frontend 20230608.0 - latest

### Example YAML snippet

```yml
type: entities 
entities:
  - type: custom:paper-buttons-row
    buttons:
      - icon: mdi:ab-testing
        tap_action:
          action: call-service
          service: media_player.play_media
          target:
            entity_id: media_player.echo_show
          data:
            media_content_id: stop
            media_content_type: custom

```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
