### ISSUE TITLE
Align individual entity icons

### ISSUE THREAD

**Issue by dnestico** [jcwillox/lovelace-paper-buttons-row#140]
Hi, I can't seem to figure out how to do it myself so just wondering if it's possible to separately align entity icons.

Here is what I have, what I would like to do as I tried to show with the arrow is just have the entity icons aligned beside each other while the time stays on the left untouched, is this possible? 

<img width="491" alt="Screenshot 2023-06-16 at 12 26 03 AM" src="https://github.com/jcwillox/lovelace-paper-buttons-row/assets/3034555/835d8bfa-1858-4297-9eee-d3d87d60ef3a">

Here is my code:

```
type: custom:paper-buttons-row
styles:
  justify-content: space-between
  background: none
  margin: 34px 20px 8px
buttons:
  - name: '{{ now().strftime(''%-I:%M'') }}'
    styles:
      name:
        font-weight: 400
        font-size: 40px
        letter-spacing: '-1px'
        margin-left: 2px
        position: relative
        left: '-10px'
      button:
        pointer-events: none
  - entity: lock.front_door
    layout: icon
    state_icons:
      unlocked: mdi:lock-open
      locked: mdi:lock
    state_styles:
      unlocked:
        button:
          color: green
      locked:
        button:
          display: none
    styles:
      button:
        background-color: none
        border-radius: 40px
        padding: 10px
        font-size: 1.2rem
    tap_action:
      action: none
  - entity: sensor.current_lights_on
    layout: icon|state
    icon: mdi:lightbulb
    color: red
    state_styles:
      '0':
        button:
          display: none
```
