### ISSUE TITLE
Sometimes buttons do not react

### ISSUE THREAD

**Issue by Larx** [jcwillox/lovelace-paper-buttons-row#16]
I file this error with paper-buttons-row, as in my setup the problem only occurs with this custom component. It might have some other issue, but it's really a bit weird:

Symptoms: Sometimes (too often) there will be no reaction to button presses in paper-buttons-row. That means, some of my cards with this setup keep on working, some don't react. This will solve itself after some time, but as of now I haven't found a rule behind this. The entities I want to control still will work when using the developper tools of home assistant or another lovelace card without paper-button-row. It seems that specific cards containing paper-button-rows will "hang" (other entity rows in the same card will still work, however). I control covers, lights and a lock with paper-buttons-row, so it's not domain-specific.

HA is installed natively (not docker) on a RPi4. Pages are served directly, no proxy (problem occured already when I was still using an Apache reverse proxy). The problem exists on all kinds of clients (Android App, Android & Linux Firefox and Chromium).

As e.g. even "condition:" fields in the YAML-code are not executed when paper-buttons-row "hangs" in a card, it looks as if the button press is not processed at all and the command does not even reach the core of HomeAssistant.

I don't see anything in the logs in this case. I suspect some strange kind of cache problem, but I really don't know where (and how) to start debugging.

Any help appreciated...

**Comment by crazyminecuber** [comment]
I appear to have the same issue.

**Comment by Larx** [comment]
I'm really quite at loss how to deal with this problem, as simple leaves no traces (for me), the paper-buttons-row buttons simple do nothing any more. Just to add: If a paper-buttons-row goes unresponsive, it is unresponsive on all my clients. So it seems rather a server-side problem.

**Comment by jcwillox** [comment]
Hmm, not sure how that would be possible. What is the state of the entities in question when this happens?

@Larx could you provide the config for one of the cards that are having this issue.

@crazyminecuber I tested your config and couldn't find any issues initially, but I'll see how it goes. Also, it didn't appear to be causing any issues but you should probably avoid having _null_ values in your config (i.e remove `button: null`).

**Comment by Larx** [comment]
One example is my front door card. It uses the Nuki integration, which currently has issues itself, but the problem occured already before, so it may serve as an example. Note the part with "condition:". If the card hangs, it doesn't work at all, it won't even open this request window. So I gather it's not a problem of the service call.

```
entities:
  - type: section
  - entity: lock.door
    name: Front door
    state_color: true
  - buttons:
      - icon: 'mdi:lock'
        name: LOCK
        tap_action:
          action: call-service
          service: lock.lock
          service_data:
            entity_id: lock.door
      - icon: 'mdi:lock-open-variant'
        name: UNLOCK
        tap_action:
          action: call-service
          service: lock.unlock
          service_data:
            entity_id: lock.door
    type: 'custom:paper-buttons-row'
  - buttons:
      - icon: 'mdi:door-open'
        name: OPEN
        tap_action:
          action: call-service
          confirmation:
            text: Really open door?
          service: lock.open
          service_data:
            entity_id: lock.door
      - icon: 'mdi:lock-plus'
        name: Lock'n'Go
        tap_action:
          action: call-service
          service: nuki.lock_n_go
          service_data:
            entity_id: lock.lock
    type: 'custom:paper-buttons-row'
    .....
title: Doors and windows
type: entities
```
The problem also occurs on my cards with covers and cover groups. I also have cards with light switches, which seem to work (?!?).

**Comment by crazyminecuber** [comment]
I have removed the null item and other lines from my buttom config. I will continue to test if something changed. But to clarify the behavior I have been observing. The problem is that sometimes, pressing the button does nothing. However, it updates just fine. For example if i change the state of the relay in some other way, the button is showing the correct state and color I want for that state. But after that, pressing the button still does nothing. I think the problem has only been observed when using the iOS app for home assistant. As previously said, the problem only occurs sometimes and when it does, it lasts for the rest of session that I use the app. So pressing it multiple times does nothing. And when the problem occurs, everything else appears as normal.

**Comment by Larx** [comment]
I can add another strange thing which I never had before: I don't know if it's another problem or the same. Only one of the buttons of a button row gives an error, all others in the same row still work!

I have a button row which contains the following lines:

```
          - icon: 'mdi:window-shutter'
            tap_action:
              action: call-service
              service: cover.set_cover_position
              service_data:
                entity_id: cover.rolladen_fz
                position: 0
          - icon: 'mdi:numeric-1-circle'
            tap_action:
              action: call-service
              service: cover.set_cover_position
              service_data:
                entity_id: cover.rolladen_fz
                position: 10          -
          - icon: 'mdi:numeric-2-circle-outline'
            tap_action:
              action: call-service
              service: cover.set_cover_position
              service_data:
                entity_id: cover.rolladen_fz
                position: 20
```
The strange thing is, the position "10" does not work! All other cover positions in same syntax still work. Also I have six more covers which I control with similar buttons. They all still accept the "10" position (why shouldn't they?). This is the first time I have this, previously it was "all or nothing" - either a paper buttons row worked or didn't work at all.

Tapping the button for position 10 in the above example gives:
```
Logger: homeassistant.components.websocket_api.http.connection.3734237072
Source: core.py:1222
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:04:26 (6 occurrences)
Last logged: 17:07:34

expected int for dictionary value @ data['position']
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1222, in async_call
    processed_data = handler.schema(service_data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['position']
Fehler beim Aufrufen des Service cover/set_cover_position. expected int for dictionary value @ data['position']
```

I have the expression that something is going weirdly wrong here :-( .
