### ISSUE TITLE
Call-service not working

### ISSUE THREAD

**Issue by poudenes** [jcwillox/lovelace-paper-buttons-row#163]
### The problem

I will use this yaml part for nice circle images with a call-service to start color scenes:

```
type: custom:paper-buttons-row
base_config:
  styles:
    icon:
      height: 90px;
      width: 90px;
buttons:
  - image: /assets/scene_presets/Adrift.jpeg
    tap_action:
      action: call-service
      service: scene_presets.start_dynamic_scene
      target: {}
      data:
        preset_id: Soho
        targets:
          entity_id:
            - light.dressoir_1
            - light.dressoir_2
            - light.dressoir_3
        brightness: 255
        transition: 4
        interval: 5
```
Bit get a error that kay part : targets is not provided.
Below normal button card is working without errors:
```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: scene_presets.start_dynamic_scene
  target: {}
  data:
    preset_id: Soho
    targets:
      entity_id:
        - light.dressoir_1
        - light.dressoir_2
        - light.dressoir_3
    brightness: 255
    transition: 4
    interval: 5
entity: switch.newkaku_014e5906_a
```

How can I use the paper-button to have a nice circle image and use the call service?

### What version of Paper Buttons Row has the issue?

2.1.3

### What version of Home Assistant are you running?

Home Assistant 2023.10.5

### What version of the Frontend are you running?

Frontend 20231005.0 - latest
