### ISSUE TITLE
Active button background color

### ISSUE THREAD

**Issue by ganjakyp-hub** [jcwillox/lovelace-paper-buttons-row#179]
### The problem

![2024-03-22_134044](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/94526141/375a9382-309b-4ffe-9b06-e91d2ce4703a)

How can I make sure that the color of a button that is turned on does not change to yellow, but remains the same as when it is turned off?

### What version of Paper Buttons Row has the issue?

2.1.3

### What version of Home Assistant are you running?

2023.12.4

### What version of the Frontend are you running?

20231208.2

### Example YAML snippet

```yml
- type: custom:paper-buttons-row
    preset: mushroom
    buttons:
      - entity: binary_sensor.192_168_10_143
        layout: icon|state
        styles:
          button:
            width: 98%
            padding: 11px 12px 10px 12px
        state_icons:
          'on': mdi:power-plug-off
          'off': mdi:power-plug
        state_text:
          'on': Выключить телевизор
          'off': Включить телевизор
        state_styles:
          'on':
            state:
              color: var(--state-active-color)
            icon:
              color: var(--state-active-color)
          'off':
            state:
              color: var(--paper-item-icon-color)
            icon:
              color: var(--paper-item-icon-color)
        tap_action:
          action: call-service
          service: scene.turn_on
          target:
            entity_id:
```
