### ISSUE TITLE
Browser Refresh issue when polulating card using auto-entities 

### ISSUE THREAD

**Issue by erkr** [jcwillox/lovelace-paper-buttons-row#184]
### The problem

Hi, 

I tried to populate thid nice card using the auto-entities card. I made a very simple setup to demonstrate:
``` 
type: custom:auto-entities
card_param: buttons
filter:
  template: |
    {%- set entities = states.input_boolean | 
        map(attribute='entity_id') | list -%}
    {{ entities }} 
  include: []
  exclude: []
card:
  type: custom:paper-buttons-row
  base_config:
    tap_action:
      action: toggle
    hold_action:
      action: more-info
show_empty: true
``` 

This only works initially, in de card editor and after saving:
![image](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/4363599/755c4346-b1ab-4c52-bcb3-b98dfebf863f)

It fails after the first browser refresh:
![image](https://github.com/jcwillox/lovelace-paper-buttons-row/assets/4363599/c62b4878-15d0-4fe6-ac05-43c53840e364)

A fix would be great

Best Eric 

### What version of Paper Buttons Row has the issue?

2.1.3

### What version of Home Assistant are you running?

2024.5.5

### What version of the Frontend are you running?

20240501.1

### Example YAML snippet

```yml
Provided
```
