### ISSUE TITLE
[FR]: Action option Entity only valid for action: more-info 

### ISSUE THREAD

**Issue by pdwonline** [jcwillox/lovelace-paper-buttons-row#195]
### Is your feature request related to a problem? Please describe.

Why not also for call service or toggle?  Especially when it comes to double tap or long tap, it would be very handy to actual do something with another entity

### Describe the solution you'd like

When I have a light button, I might want to toggle the light entity itself, but also toggle the light-automation on or off by a tap hold action for example.

```
    buttons:
      - entity: light.livingroom
        icon: mdi:lightbulb-group
        hold_action:
           action: toggle
           entity: automation.light_livingroom
```
