### ISSUE TITLE
state_styles seems not to work with a input_select

### ISSUE THREAD

**Issue by pdwonline** [jcwillox/lovelace-paper-buttons-row#200]
### The problem

I use an input_select helper to set a heating mode. like this:

<img width="440" alt="afbeelding" src="https://github.com/user-attachments/assets/21f58bac-583e-4490-9451-70addaa0cafb" />

The yaml is below:
```   
- type: custom:paper-buttons-row
    base_config:
      preset: ha_button
      layout: icon_name
      style:
        button:
          background-color: var(--table-row-alternative-background-color)
          border-radius: 10px
          width: 100%
          margin: 4px
          height: 50px
          padding: 3px
        name:
          color: gray
          font-size: 80%
        icon:
          color: var(--state-icon-color)
      double_tap_action:
        action: none
    buttons:
      - entity: sensor.temperature_req_generic
        name: false
        icon: mdi:thermometer-plus
        state: "{{ states(\"sensor.temperature_req_generic\")}}°C"
        style:
          state:
            font-size: 80%
          button:
            background-color: var(--card-background-color)
            color: >
              {% if states("sensor.temperature_req_generic") |float(0) > 0 %}  
              var(--state-active-color) {% else %} var(--disabled-color) {%endif
              %}
          icon:
            color: >
              {% if states("sensor.temperature_req_generic") |float(0) > 0 %}  
              var(--state-active-color) {% else %} var(--disabled-color) {%endif
              %}  
        tap_action:
          action: none
        layout: icon_state
      - entity: input_select.thermostat_indicator_generic
        name: Comfort
        icon: mdi:radiator
        state_styles:
          "on":
            icon:
              color: var(--state-active-color)
        style:
          icon:
            color: >-
              {% if is_state('input_select.thermostat_indicator_generic',
              'Comfort') %} var(--state-active-color){%else%} 
              var(–paper-item-icon-color){%endif%}
        tap_action:
          action: call-service
          service: script.climate_comfort
      - entity: sensor.placeholder
        icon: mdi:leaf
        name: Eco
        style:
          icon:
            color: >-
              {% if is_state('input_select.thermostat_indicator_generic',
              'Eco')%} var(--state-active-color){%else%} 
              var(–paper-item-icon-color){%endif%}
        tap_action:
          action: call-service
          service: script.climate_eco
      - entity: sensor.placeholder
        name: Spaarstand
        icon: mdi:weather-night
        style:
          icon:
            color: >-
              {% if is_state('input_select.thermostat_indicator_generic',
              'Spaarstand')%} var(--state-active-color){% else%} 
              var(–paper-item-icon-color){% endif %}
        tap_action:
          action: call-service
          service: script.climate_night
``` 

As you can see, I set the color of the selected mode active using a CSS style like this:

```
        style:
          icon:
            color: >-
              {% if is_state('input_select.thermostat_indicator_generic',
              'Eco')%} var(--state-active-color){%else%} 
              var(–paper-item-icon-color){%endif%}
```

That works, but is quite slow responding. So i would like to use state_styles instead like this:

```
     - entity: input_select.thermostatmode_living
        icon: mdi:leaf
        name: Eco
        state_styles:
          "on":
            icon:
              color: var(--state-active-color)
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            option: Eco
          target:
            entity_id: input_select.thermostatmode_living
 ```

However, that seems not to work. Why?
