### ISSUE TITLE
Paper Buttons Row does not respect all "Show as" settings in the cover domain...

### ISSUE THREAD

**Issue by Jaxel** [jcwillox/lovelace-paper-buttons-row#201]
### The problem

The default state icons for cover entities are `mdi:window` and `mdi:window-closed`.

However, cover entities have a setting for "Show as". This dropdown changes the state icons of your entity. This works fine in Paper Buttons Row with Show as settings of "Blinds, "Door, "Garage Door", "Shutter" and "Window". However, if you select any of the other settings, such as "Awning", "Curtain", "Damper", "Gate" or "Shade",  Paper Buttons Row will not show the proper state icons and will instead show the default window icons.

![Overview-–-Home-Assistant-01-08-2025_06_16_AM](https://github.com/user-attachments/assets/285ac310-f683-4d31-94d6-6cd40097db50)
![Overview-–-Home-Assistant-01-08-2025_06_13_AM](https://github.com/user-attachments/assets/927603c7-6d56-4aa0-ac9e-c125d271dbf9)

In addition, Paper Buttons Row does not show the colors of the state. Open covers are supposed to be purple.

### What version of Paper Buttons Row has the issue?

2.2.0

### What version of Home Assistant are you running?

2025.1.1

### What version of the Frontend are you running?

20250106.0

### Example YAML snippet

```yml
- entity: light.light_switch_patio
    name: Patio
    icon: mdi:pool
    tap_action:
      action: toggle
    extend_paper_buttons_row:
      hide_state: true
      base_config:
        layout: icon
      buttons:
        - entity: fan.fan_switch_patio
        - entity: cover.shade_patio
        - entity: light.light_switch_patio
```
