### ISSUE TITLE
Feature Request: state_text templating & state or attribute values

### ISSUE THREAD

**Issue by ktownsend-personal** [jcwillox/lovelace-paper-buttons-row#21]
I have a scenario that requires formatting an attribute value given as total seconds to HH:MM. I am currently using a `template-entity-row` for this, but it has a large gap between the icon and the formatted text. It's also not nearly as flexible as your `paper-buttons-row`. 

I just started using `paper-buttons-row` today on my `picture elements` card for managing my pool system, and it's working great for many of my icon+state buttons. The proposed features below would make this element work for the rest of my pool console, and it will look far better than any other element I have experimented with. Not to mention making my config simpler.

Adding the ability to use templating in the state_text values would work great for my scenario. To account for a configured entity that doesn't have discrete states, such as temperature or seconds, we can define a template directly on the `state_text` config instead of defining a state value map. Alternatively, a simple shorthand for showing raw state without a template could be a value of `true` instead of a template or a map. The same pattern can be used for mapped states too. 

To round it off, a new config option for an attribute name on the configured entity would be handy. If the attribute config is given, it is used instead of the entity state. Pair that with a unit suffix config and most simple cases can avoid templates. 

Within a template, it would be convenient to have an object available that references the configured entity. This isn't a necessary feature, but it would be convenient to reference `entity.state` instead of `states('sensor.pool_temperature')`. I believe I've seen this done someplace, but don't recall exactly where off the top of my head. I certainly wouldn't be complaining if this convenience was missing but the rest was available :)

```yaml
# example of my scenario using a templated value on a state_text map:

- type: 'custom:paper-buttons-row'
  buttons:
    - entity: switch.sprinkler_zone_12
      icon: mdi:water-pump
      state_text:
        'off': fill pool one inch
        'on': >
          {% set s = (state_attr('switch.sprinkler_zone_12', 'time_remaining')|int) %}
          {% set h = (s / 3600) %}
          {% set m = (s % 3600) / 60 %} 
          {{ "%02d:%02d" % (h,m) }}
      tap_action:
        action: call-service
        service: rainmachine.start_zone
        service_data:
          zone_id: 13
          zone_run_time: 7200
```
```yaml
# example of proposed attribute & unit config, and specifying true for state_text

- type: 'custom:paper-buttons-row'
  buttons:
    - entity: climate.pool_heater
      attribute: temperature
      unit: °F
      state_text: true
```
```yaml
# example of using a template value without a state map, and a shorthand keyword for the configured entity reference:

- type: 'custom:paper-buttons-row'
  buttons:
    - entity: sensor.spa_temperature
      state_text: "{{ entity.state }} in the spa, heating to {{ state_attr('climate.spa_heater', 'set_point') }}"
```
