### ISSUE TITLE
TypeError: r.state.toLowerCase is not a function

### ISSUE THREAD

**Issue by GeertGK** [jcwillox/lovelace-paper-buttons-row#212]
### The problem

I'm trying everything to get this working, however I only keep getting these errors in the console.
I'm using my own code, but also tried it with the sample code below, both give the same probelm.

### What version of Paper Buttons Row has the issue?

2.2.0

### What version of Home Assistant are you running?

2025.4.3

### What version of the Frontend are you running?

20250411.0

### Example YAML snippet

```yml
type: entities
entities:
  - type: custom:paper-buttons-row
    # apply to all buttons
    preset: mushroom
    base_config:
      # the same as above applies to all buttons
      preset: mushroom
    buttons:
      - entity: light.bedroom_light
        # or override on a button level
        preset: mushroom

      - entity: lock.front_door
        # set what state is considered active
        active: unlocked
        styles:
          # override the inactive color
          --pbs-button-rgb-color: red
          # override the active color
          --pbs-button-rgb-active-color: green

      - icon: mdi:power
```

### Anything in the logs that might be useful for us?

```python3
paper-buttons-row.js…g=244872232220:1604 Uncaught (in promise) TypeError: r.state.toLowerCase is not a function
    at z._getStyles (paper-buttons-row.js…44872232220:1604:38)
    at paper-buttons-row.js…4872232220:1482:144
    at Array.map (<anonymous>)
    at paper-buttons-row.js…44872232220:1480:17
    at Array.map (<anonymous>)
    at z.render (paper-buttons-row.js…44872232220:1473:30)
    at z.update (paper-buttons-row.js…244872232220:804:20)
    at z.performUpdate (paper-buttons-row.js…244872232220:513:16)
    at z.scheduleUpdate (paper-buttons-row.js…244872232220:501:17)
    at z.<anonymous> (paper-buttons-row.js…244872232220:496:22)
_getStyles	@	paper-buttons-row.js…g=244872232220:1604
(anonymous)	@	paper-buttons-row.js…g=244872232220:1482
(anonymous)	@	paper-buttons-row.js…g=244872232220:1480
render	@	paper-buttons-row.js…g=244872232220:1473
update	@	paper-buttons-row.js…ag=244872232220:804
performUpdate	@	paper-buttons-row.js…ag=244872232220:513
scheduleUpdate	@	paper-buttons-row.js…ag=244872232220:501
(anonymous)	@	paper-buttons-row.js…ag=244872232220:496
o	@	paper-buttons-row.js…tag=244872232220:22
Promise.then		
c	@	paper-buttons-row.js…tag=244872232220:26
(anonymous)	@	paper-buttons-row.js…tag=244872232220:27
me	@	paper-buttons-row.js…tag=244872232220:13
_$Ej	@	paper-buttons-row.js…ag=244872232220:489
requestUpdate	@	paper-buttons-row.js…ag=244872232220:486
Ie.mr.template	@	paper-buttons-row.js…g=244872232220:1319
r.subscribeMessage.type	@	paper-buttons-row.js…g=244872232220:1276
```
