### ISSUE TITLE
When using extend_paper_buttons_row, the tap_action is triggered when clicking on a paper-button since HA 2025.5

### ISSUE THREAD

**Issue by Otiel** [jcwillox/lovelace-paper-buttons-row#214]
### The problem

Since HA 2025.5, when using `extend_paper_buttons_row`, the actions ([`tap_action`](https://www.home-assistant.io/dashboards/entities#tap_action), `hold_action` and `double_tap_action`) of the entity is triggered when clicking on a paper-button. There was no issue with HA ≤ 2025.4.x.

See this video, where the more-info dialog is opened (I have `tap_action: action: more-info`) when I click on my paper-button:

https://github.com/user-attachments/assets/6187ee10-cf3f-4cbd-8a6e-ed16dd6e3e04

This issue has been reported by several users on [Home Assistant Community forums](https://community.home-assistant.io/t/add-a-button-to-the-default-cover-entity-card/438243/8).

### What version of Paper Buttons Row has the issue?

2.2.0

### What version of Home Assistant are you running?

2025.5.3

### What version of the Frontend are you running?

20250516.0

### Example YAML snippet

```yml
type: entities
entities:
  - entity: cover.shutter_office
    tap_action:
      action: more-info
    extend_paper_buttons_row:
      buttons:
        - icon: mdi:weather-sunset-down
          tap_action:
            action: call-service
            service: script.open_office_shutter_to_sun_position
```

### Anything in the logs that might be useful for us?

Note sure if that's relevant, but I've got the following error:

```python3
unexpected parent node found paper-buttons-row.js:1347:342
    <anonymous> paper-buttons-row.js:1347
    firstUpdated paper-buttons-row.js:1331
    _$AE reactive-element.ts:1550
    performUpdate reactive-element.ts:1517
    scheduleUpdate reactive-element.ts:1399
    _$EP reactive-element.ts:1371
    requestUpdate reactive-element.ts:1310
    _$Ev reactive-element.ts:1055
    C reactive-element.ts:1038
    i lit-element.ts:130
    b hui-generic-entity-row.ts:22
    I scoped-custom-element-registry.ts:642
    t scoped-custom-element-registry.ts:408
    u lit-html.ts:1218
    $ lit-html.ts:1639
    _$AI lit-html.ts:1475
    j lit-html.ts:2274
    update lit-element.ts:171
    performUpdate reactive-element.ts:1503
    scheduleUpdate reactive-element.ts:1399
    _$EP reactive-element.ts:1371
    requestUpdate reactive-element.ts:1310
    set reactive-element.ts:789
    setConfig hui-cover-entity-row.ts:24
    u create-element-base.ts:219
    (Async: promise callback)
    u create-element-base.ts:214
    u create-element-base.ts:308
    d create-element-base.ts:242
    b create-row-element.ts:107
    _renderEntity hui-entities-card.ts:290
    render hui-entities-card.ts:216
    render hui-entities-card.ts:215
    update lit-element.ts:166
    performUpdate reactive-element.ts:1503
    scheduleUpdate reactive-element.ts:1399
    _$EP reactive-element.ts:1371
    requestUpdate reactive-element.ts:1310
    _$Ev reactive-element.ts:1055
    C reactive-element.ts:1038
    i lit-element.ts:130
    g hui-entities-card.ts:27
    I scoped-custom-element-registry.ts:642
    t scoped-custom-element-registry.ts:408
    a create-element-base.ts:149
    u create-element-base.ts:312
    d create-element-base.ts:242
    _ create-card-element.ts:108
    _loadElement hui-card.ts:123
    load hui-card.ts:42
    _createCardElement hui-section.ts:81
    _cards hui-section.ts:337
    _createCards hui-section.ts:336
```

**Comment by narf0815** [comment]
i can confirm this behavior.

**Comment by jumpinf00l** [comment]
Temporary workaround I found is to set the tap_action to none on the parent entity, and then use either hold_action or double_tap_action for more-info. Not perfect, but workable until this is fixed.

Example using hold_action on the parent entity:

```
type: entities
entities:
  - entity: light.dining_room_table_lamp
    tap_action: 
      action: none
    hold_action: 
      action: more-info
    extend_paper_buttons_row:
      position: left
      buttons:
        - show_name: true
          name: Restore defaults
          type: button
          tap_action:
            action: call-service
            service: light.turn_on
            target:
              entity_id: light.dining_room_table_lamp
            service_data:
              brightness_pct: 100
              kelvin: 3000
```
