### ISSUE TITLE
Change event not fired on button press

### ISSUE THREAD

**Issue by Alfiegerner** [jcwillox/lovelace-paper-buttons-row#22]
Hi,

I have the following lovelace:
```
                entities:
                  - entity: input_text.search_kodi
                    type: 'custom:text-input-row'
                  - buttons:
                      - icon: 'mdi:movie'
                        name: Movies
                        tap_action:
                          action: call-service
                          service: script.search_kodi_movies
                      - icon: 'mdi:television'
                        name: TV shows
                        tap_action:
                          action: call-service
                          service: script.search_kodi_shows
                    type: 'custom:paper-buttons-row'
                type: entities
```

A text entry field, which has two buttons underneath, one to search for movies and one for TV shows.

With the predecessor button-entity-row component clicking the buttons would cause a change event to be triggered on ``` input_text.search_kodi``` causing the search text to be updated , so that the search was successful.

With paper-buttons-row the input_text field is not updated if i press the button directly after typing (on android but may occur elsewhere), but works fine if I tap somewhere else in the panel and then hit the button.

Any ideas welcome, thanks.
