### ISSUE TITLE
call service input_select.select_option

### ISSUE THREAD

**Issue by bachy** [jcwillox/lovelace-paper-buttons-row#24]
Hi,

i'm quite new to hass and i need some help to setup a serie of buttons to select an input_select option
here is what i tried, without success so far
```yaml
entities:
  - entity: input_select.mode_chauffage_general
  - type: 'custom:paper-buttons-row'
    buttons:
      - icon: 'mdi:radiator-off'
        tap_action: call_service
        service: input_select.select_option
        entity_id: input_select.mode_chauffage_general
        service_data: 
          option: "Arrêt"
      - icon: 'mdi:snowflake'
        tap_action: call_service
        service: input_select.select_option
        service_data: 
          entity_id: input_select.mode_chauffage_general
          option: "Hors-Gel"
      - icon: 'mdi:moon-waxing-crescent'
        tap_action: call_service
        service: input_select.mode_chauffage_general
        service_data: { "option": "Eco" }
      - icon: 'mdi:white-balance-sunny'
        tap_action: call_service
        service: input_select.select_option
        service_data: 
          entity_id: input_select.mode_chauffage_general
          option: Confort
```

**Comment by jcwillox** [comment]
Hey, so your config is not valid, have a look at the documentation and examples they should help. The main issue is the way you defined your actions, Paper Buttons Row uses the same action configurations that Home Assistant does, have a look at their [action docs](https://www.home-assistant.io/lovelace/actions).

This config should be valid, note that if you define an `entity_id` for the button it will automatically be added to the service data, but you can also manually set it for the `service_data`.
```yaml
entities:
  - entity: input_select.mode_chauffage_general
  - type: 'custom:paper-buttons-row'
    buttons:
      - icon: 'mdi:radiator-off'
        entity_id: input_select.mode_chauffage_general
        tap_action: 
          action: call_service
          service: input_select.select_option
          service_data: 
            option: "Arrêt"
      - icon: 'mdi:snowflake'
        entity_id: input_select.mode_chauffage_general
        tap_action: 
          action: call_service
          service: input_select.select_option
          service_data: 
            option: "Hors-Gel"
      - icon: 'mdi:moon-waxing-crescent'
        tap_action: 
          action: call_service
          service: input_select.mode_chauffage_general
          service_data: { "option": "Eco" }
      - icon: 'mdi:white-balance-sunny'
        entity_id: input_select.mode_chauffage_general
        tap_action: 
          action: call_service
          service: input_select.select_option
          service_data: 
            option: Confort
```

**Comment by bachy** [comment]
Hi thank you for your answer!
but the fact is i already corrected my card, and it's not working better
```yaml
type: entities
entities:
  - entity: input_select.mode_chauffage_general
    icon: false
  - type: 'custom:paper-buttons-row'
    buttons:
      - entity: input_select.mode_chauffage_general
        name: false
        icon: 'mdi:radiator-off'
        tap_action:
          action: call_service
          service: input_select.select_option
          service_data:
            option: "Arrêt"
        state_styles:
          Arrêt:
            button:
              color: yellow
      - entity: input_select.mode_chauffage_general
        name: false
        icon: 'mdi:snowflake'
        tap_action:
          action: call_service
          service: input_select.select_option
          service_data:
            option: "Hors-Gel"
        state_styles:
          Hors-Gel:
            button:
              color: yellow
      - entity: input_select.mode_chauffage_general
        name: false
        icon: 'mdi:moon-waxing-crescent'
        tap_action:
          action: call_service
          service: input_select.select_option
          service_data:
            option: "Eco"
        state_styles:
          Eco:
            button:
              color: yellow
      - entity: input_select.mode_chauffage_general
        name: false
        icon: 'mdi:white-balance-sunny'
        tap_action:
          action: call_service
          service: input_select.select_option
          service_data:
            option: Confort -2
        state_styles:
          Confort -2:
            button:
              color: yellow
      - entity: input_select.mode_chauffage_general
        name: false
        icon: 'mdi:white-balance-sunny'
        tap_action:
          action: call_service
          service: input_select.select_option
          service_data:
            option: Confort -1
        state_styles:
          Confort -1:
            button:
              color: yellow
      - entity: input_select.mode_chauffage_general
        name: false
        icon: 'mdi:white-balance-sunny'
        tap_action:
          action: call_service
          service: input_select.select_option
          service_data:
            option: "Confort"
        state_styles:
          Confort:
            button:
              color: yellow
  - entity: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level_2
    secondary_info: brightness
    name: salon
    icon: 'mdi:radiator'
  - entity: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level
    icon: 'mdi:radiator'
    secondary_info: brightness
    name: sdb rdc
  - entity: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level_3
    icon: 'mdi:radiator'
    name: sdb 1er
    secondary_info: brightness
  - entity: light.fp_qubino_chambre_1_level_4
    icon: 'mdi:radiator'
    name: chambre 1
    secondary_info: brightness
  - entity: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level_5
    name: qubino
    icon: 'mdi:radiator'
    secondary_info: brightness
title: Chauffage
state_color: true
```
while with custom:button-card is working
```yaml
- type: 'custom:stack-in-card'
    mode: horizontal
    cards:
      - type: 'custom:button-card'
        entity: input_select.mode_chauffage_general
        show_name: false
        icon: 'mdi:radiator-off'
        show_label: false
        tooltip: Arrêt
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.mode_chauffage_general
            option: Arrêt
        state:
          - value: Arrêt
            color: blue
      - type: 'custom:button-card'
        entity: input_select.mode_chauffage_general
        show_name: false
        icon: 'mdi:snowflake'
        show_label: false
        tooltip: Hors-Gel
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.mode_chauffage_general
            option: Hors-Gel
        state:
          - value: Hors-Gel
            color: blue
      - type: 'custom:button-card'
        entity: input_select.mode_chauffage_general
        show_name: false
        icon: 'mdi:moon-waxing-crescent'
        show_label: false
        tooltip: Confort
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.mode_chauffage_general
            option: Eco
        state:
          - value: Eco
            color: yellow
      - type: 'custom:button-card'
        entity: input_select.mode_chauffage_general
        show_name: false
        icon: 'mdi:white-balance-sunny'
        show_label: false
        tooltip: Confort -2
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.mode_chauffage_general
            option: Confort -2
        state:
          - value: Confort -2
            color: yellow
      - type: 'custom:button-card'
        entity: input_select.mode_chauffage_general
        show_name: false
        icon: 'mdi:white-balance-sunny'
        show_label: false
        tooltip: Confort -1
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.mode_chauffage_general
            option: Confort -1
        state:
          - value: Confort -1
            color: yellow
      - type: 'custom:button-card'
        entity: input_select.mode_chauffage_general
        show_name: false
        icon: 'mdi:white-balance-sunny'
        show_label: false
        tooltip: Confort
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.mode_chauffage_general
            option: Confort
        state:
          - value: Confort
            color: yellow
```
