### ISSUE TITLE
paper-buttons-row does not work in Chrome (updated)

### ISSUE THREAD

**Issue by acmkonings** [jcwillox/lovelace-paper-buttons-row#30]
I basically copied the example, and it didn't seem to have an effect on the lovelace frontend, but then I opened the app and there it  was, in full glory! When I checked however, it still was not reflected in the ui (browser).

```
type: entities
entities:
  - entity: fan.wtw_eenheid
    extend_paper_buttons_row:
      buttons:
        - entity: script.fan_1
          icon: 'mdi:track-light'
        - entity: script.fan_2
          icon: 'mdi:all-inclusive'
          name: nummer 2
        - entity: script.fan_3
          icon: 'mdi:brightness-3'
          name: nummer 3
```

Maybe I am overlooking something?

Version: HA core 2020.12.1, paper-buttons-row: latest

Update: I've tracked it down to be a browser-issue: Edge works fine, Chrome is missing the extended icons completely. Both are current versions to my knowledge.

Update 2: I've installed Firefox, it works here as intended also. Furthermore it has gotten clear that the Chrome browser is claiming that: 

```
Custom element doesn't exist: paper-buttons-row.
type: 'custom:paper-buttons-row'
```
