### ISSUE TITLE
Icon color change on tap

### ISSUE THREAD

**Issue by Yavenn** [jcwillox/lovelace-paper-buttons-row#31]
Hi,
I tried to find this feature, but i was able to change color only on state "on" and "off.
Is there an option to change color only on tap, so it will lit once pressed and then released?
It would be also nice to be able to apply value for delay.

Thank you,

**Comment by jcwillox** [comment]
This is not currently possible, I would like to add the ability to style the `hover` and `active` CSS states, but that will take quite a bit of work given the current codebase.
It might be somewhat achievable using card-mod.

**Comment by jcwillox** [comment]
Since the [1.0.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/1.0.0) release, you can use `extra_styles` to define hover and active effects for the buttons.

**Comment by dodekaphilist** [comment]
Could you provide an example for how to implement a custom hover state? I'm struggling with that and there's no example in the README.md

**Comment by jcwillox** [comment]
Sure it's actually quite easy with a little CSS, you can even style individual buttons using selectors like `nth-child(n)`.

```yaml
  - type: custom:paper-buttons-row
    extra_styles: |
      paper-button:hover {
        background-color: red;
      }
      paper-button:active {
        background-color: yellow;
      }
      /* styles for the second button only */
      paper-button:nth-child(2):hover {
        background-color: green;
      }
      paper-button:nth-child(2):active {
        background-color: purple;
      }
    buttons:
      - icon: mdi:power
      - icon: mdi:power
```
