### ISSUE TITLE
Runn script

### ISSUE THREAD

**Issue by premiums73** [jcwillox/lovelace-paper-buttons-row#32]
Hi everyone, I'm new to the forum.

I can run a script ?

**Comment by jcwillox** [comment]
I'm not sure what you mean?
Do you mean running a Home Assistant script, you can do that with a service call action.
```yaml
type: entities
entities:
  - type: "custom:paper-buttons-row"
    buttons:
      - entity: light.bedroom
        tap_action:
          action: call-service
          service: script.my_script
```
