### ISSUE TITLE
State text not showing anymore

### ISSUE THREAD

**Issue by silfax** [jcwillox/lovelace-paper-buttons-row#35]
Hi,
As the title says, the state text is not showing anymore, just the icon is displayed. Don't know when it happened, it's my lawn sprinkler valve which is "off" since September.
``` 
 - entity: switch.sonoff_1000xxxxxx
   name: false
   state_icons:
     'off': 'mdi:water-off-outline'
     'on': 'mdi:sprinkler-variant'
   state_styles:
     'off':
       icon:
         color: red
       text:
         color: red
     'on':
       icon:
         color: green
       text:
         color: green
   state_text:
     'off': Sprinkler off
     'on': Sprinkler on
```
Everything is updated to the last builds.

Thanks!

**Comment by larswnd** [comment]
Look at the release notes:
https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.5.0

Breaking change. You have to add (inside yout entity):
e.g.
layout: icon|state

**Comment by silfax** [comment]
Thanks, text is back! However: using "state_name" instead of "state_text" only shows "on"/"off", not my custom text assigned to the corresponding states. Using "state_text" I still get the custom text, but I cannot apply any style (color doesn't change accordingly). It looks like there is some inconsistency between "text" and "name". Will keep on trying, maybe I'm getting something wrong.

**Comment by jcwillox** [comment]
The `state_text` option was not renamed as it refers to the state and has nothing to do with the name (I mean I could've called it something like `state_map` but that seemed unnecessary).

**Comment by jcwillox** [comment]
Just to reiterate, the only breaking changes in `0.5.0` were that the `state` is now in its own field and to show it you need to use the new layout option e.g. `layout: icon|state`. The `state_text` option is the same, just it now applies to the `state` field. The final change was that in the `style` and `state_styles` fields `text` which previously applied to the `name` was renamed to `name` and a new option `state` was added to style the `state` field.

```yaml
layout: icon|state

state_text:      # unchanged but applies to the state field now
  "on": "yes"
  "off": "no"

style:
  name:
    color: red   # applies to the name field
  state:
    color: blue  # applies to the state field
```

**Comment by silfax** [comment]
Thanks a lot for all your help, I (finally) got it now! From my point of view you may consider it closed.

**Comment by caiosweet** [comment]
I don't know if it's a bug or is it intended, but in the state_text option, the state must always be entered in lowercase!

For example if the state is "Infrared" or "North West Burze"
this does not work
```
state_text:
  "Infrared": "Night"
  "North West Burze": "Burze NW"
```

while this works:
```
state_text:
  "infrared": "Night"
  "north west burze": "Burze NW"
```

**Comment by jcwillox** [comment]
Yeah, this is intended, I did it for backwards compatibility (there's a more technical reason why I chose to do it that way). Basically `state_text` and `state_styles` always use the lowercase version of the state, I'll make sure this is clearly mentioned in the docs. Alternatively, I might look into making it case-insensitive.

**Comment by caiosweet** [comment]
Ok, I think a clarification of the document is right, sure using case-insensitive would be optimal, but I find an inconsistency in state_icon, where it does not accept this concept of everything in lowercase.

Do you know this? Here, for example, I have to insert this way

```
      - entity: input_select.default_alexa_type
        layout: icon|state
        state_icons:
          "TTS": "mdi:text-shadow"
          "Push": "mdi:cellphone-text"
          "Dropin": "mdi:form-dropdown"
```

otherwise if I put everything in lowercase it doesn't change the icons.

Anyway thanks for your attention.
