### ISSUE TITLE
Switch is trimmed on mobile when buttons row is embedded into entity

### ISSUE THREAD

**Issue by greanmurk** [jcwillox/lovelace-paper-buttons-row#36]
Hi!

I try to make a row of buttons embedded into light switch entity and found small issue with switch positioning on android mobile device. 

Here is config;
```
type: entities
entities:
  - entity: switch.24333817a4cf12a01461
    icon: 'mdi:ceiling-light'
    name: Ceiling light
    extend_paper_buttons_row:
      buttons:
        - entity: script.switch_chandelier_aux
          icon: 'mdi:led-on'
          name: false
        - entity: script.switch_chandelier_low
          icon: 'mdi:brightness-4'
          name: false
        - entity: script.switch_chandelier_high
          icon: 'mdi:brightness-6'
          name: false
        - entity: script.switch_chandelier_all
          icon: 'mdi:brightness-5'
          name: false
          style:
            button:
              margin-right: 8px
    state_color: true
```

This is how it looks on desktop:

![Image_20210218_185727](https://user-images.githubusercontent.com/18441525/108389150-7016e280-7220-11eb-98c7-b941dbbb7297.png)

And here as on mobile, switch is trimmed:

![Screenshot_2021-02-18-18-58-46-072_io homeassistant companion android](https://user-images.githubusercontent.com/18441525/108389246-891f9380-7220-11eb-967a-24e3ab70499a.png)

Switch stop trimming only when I put -4px margin, but in this case buttons become too close to switch. Increasing margin value lead to even more trimming.

I also tried other entity (sensor), it's not trimmed, but cause state's text wrapping.

The version of HA is 2021.2.3, extension 0.5.0.
