### ISSUE TITLE
state color change 

### ISSUE THREAD

**Issue by JPOliveGit** [jcwillox/lovelace-paper-buttons-row#39]
is it possible to make a state change within a range, example: 
temperature one color if inferior than 20 and another if bigger than 20?

**Comment by jcwillox** [comment]
Sounds like you're looking for [templating](https://github.com/jcwillox/lovelace-paper-buttons-row#jinja-templates), specifically Jinja templates should allow you to do that, there's also the Home Assistant [templating](https://www.home-assistant.io/docs/configuration/templating) docs, here's an example:

```yaml
type: entities
entities:
  - type: 'custom:paper-buttons-row'
    buttons:
      - entity: sensor.temperature
        style:
          button:
            color: |-
              {% if states(entity) | float > 20 %}
                red
              {% else %}
                green
              {% endif %}
```
