### ISSUE TITLE
Use Templates in paper buttons row

### ISSUE THREAD

**Issue by cmd-sam** [jcwillox/lovelace-paper-buttons-row#4]
Is it possible to add a custom text with templates? maybe in combination with template entity row? I havent found a working way yet.

**Comment by jcwillox** [comment]
Do you mean like [`state_text`](https://github.com/jcwillox/lovelace-paper-buttons-row#using-state-icons-state-text-and-actions)? 

If your talking about this [`template-entity-row`](https://github.com/thomasloven/lovelace-template-entity-row) it is designed for templating a generic entity row it is not for configuration templating and so wouldn't make sense in this context.

There are other proper configuration template cards which should work just search for "template" in HACS.

**Comment by cmd-sam** [comment]
I mean a dynamic text in my button from a sensor. Maybe in combination with state text.

**Comment by jcwillox** [comment]
I'm going to close this as it is basically what #3 is looking at, the discussion can be continued there. 

For now, the best way to do dynamic text would be using a template card, here's a quick example using `config-template-card` it doesn't work perfectly but does achieve the desired outcome.

```yaml
type: 'custom:config-template-card'
entities:
  - sensor.bedroom_temperature
  - light.monitor_leds
card:
  type: entities
  entities:
    - type: 'custom:paper-buttons-row'
      buttons:
        - entity: light.monitor_leds
          name: '${"Monitor Leds: " + states["sensor.bedroom_temperature"].state + " °C" }'
```
