### ISSUE TITLE
How to pass `target` when calling a service?

### ISSUE THREAD

**Issue by denilsonsa** [jcwillox/lovelace-paper-buttons-row#40]
I believe recent Home Assistant versions added support for `target` when calling a service:

* https://github.com/home-assistant/home-assistant.io/pull/15891/files
* https://www.home-assistant.io/blog/2021/03/03/release-20213/#new-ui-for-service-calls
* https://github.com/home-assistant/home-assistant.io/issues/16992

However, I can't find a way to do so when using this custom component. The following example works in [the developer tools page](https://my.home-assistant.io/redirect/developer_services/):

```yaml
service: light.turn_on
data:
  transition: 60
  color_temp: 450
  brightness_pct: 100
target:
  entity_id:
    - light.foo
    - light.bar
```

And the following code works using the built-in `buttons` type:

```yaml
type: entities
entities:
  - type: buttons
    entities:
      - entity: light.bedroom_lights
        name: 1min
        icon: 'mdi:lightbulb-on'
        tap_action:
          action: call-service
          service: light.turn_on
          service_data:
            transition: 60
            color_temp: 450
            brightness_pct: 100
          target:
            entity_id:
              - light.bedroom_lights
              - light.foobar
…
```

But I am unable to add `target` to `custom:paper-buttons-row`.

**Comment by jcwillox** [comment]
Hmm, yes `target` is not a supported option of `tap_action` at least in `paper-buttons-row` that's something I'll have to implement. Interestingly it's not listed on Home Assistants [action docs](https://www.home-assistant.io/lovelace/actions/#tap-action), but I agree that it is working on the built-in cards.

**Comment by denilsonsa** [comment]
> Interestingly it's not listed on Home Assistants [action docs](https://www.home-assistant.io/lovelace/actions/#tap-action)

Yep, I've already reported it: https://github.com/home-assistant/home-assistant.io/issues/16992

**Comment by ristomatti** [comment]
Any update? Logitech Harmony Hub remote requires this also. As a workaround I can create a script for each button but that's a lot of scripts! Maybe there's some better alternative but I'm just few weeks into HA. :slightly_smiling_face:

**Comment by ristomatti** [comment]
If it's any help, the usage seems to be documented [here](https://github.com/home-assistant/home-assistant-js-websocket/blob/06ccbd270d0841bf3647a4150617d1d1a358a7a5/README.md?plain=1#L411) and used included in [this example](https://github.com/home-assistant/home-assistant-js-websocket/blob/fdbeeee943e7f89f80db84ce2a42a41db9120be3/example.html#L78).

**Comment by ristomatti** [comment]
I decided to give it a shot and it seems I got it working, I'll create a PR. The funny thing is that this was not actually needed for my use case after all. I had the config set like this:

```yaml
action: call-service
service: remote.send_command
service_target:
  device_id: a6015bda1dfaf2b5a38f7eefeb050c06
service_data:
  device: '37034509'
  command: 'FanSpeedUp'
```

...instead of this:

```yaml
tap_action:
  action: call-service
  service: remote.send_command
  service_target:
    device_id: a6015bda1dfaf2b5a38f7eefeb050c06
  service_data:
    device: '37034509'
    command: 'FanSpeedUp'
```

:man_facepalming:
