### ISSUE TITLE
Not to change name color on state

### ISSUE THREAD

**Issue by FaBRiK74** [jcwillox/lovelace-paper-buttons-row#44]
I couldn't find a solution not to change the text (name) of the button based on state. I mean I just want to leave it on the original theme based color but change only the icon color. Now if I turn on a switch the name color also changes based on state.

**Comment by jcwillox** [comment]
The default has always been for the name (and the whole button) to change color based on state. However, you can disable this by setting the `color` CSS property to some fixed value or a CSS variable like `var(--paper-item-icon-color)`, the example below will prevent the name from changing color, and allow the icon to change color based on state.

```yaml
type: entities
entities:
  - type: "custom:paper-buttons-row"
    buttons:
      - entity: light.desk_leds
        icon: "mdi:lightbulb"
        style:
          name:
            color: var(--paper-item-icon-color)
```
