### ISSUE TITLE
alarm_control_panel icon doen't show

### ISSUE THREAD

**Issue by FaBRiK74** [jcwillox/lovelace-paper-buttons-row#45]
The alarm_control_panel entity has a changing icon based on state. When I add the alarm_control_panel entity under "buttons:", the icon disappears. If I put the same code right under "entities:" it works normally. See the attached screenshot. On the upper side there is a normal entity glance card with the same entity "Riasztó" and on the bottom the missing icon in Paper Buttons Row with the same code below.
![alarm icon](https://user-images.githubusercontent.com/78682753/114823544-f59fb480-9dc3-11eb-8135-39fe67ddaef0.jpg)

And the code:
```yaml
type: entities
entities:
  - type: 'custom:paper-buttons-row'
    buttons:
      - entity: alarm_control_panel.riaszto
        name: Riasztó
        state_color: true
        tap_action:
          action: navigate
          navigation_path: biztonsag
```
