### ISSUE TITLE
Button Flex Display

### ISSUE THREAD

**Issue by joinke** [jcwillox/lovelace-paper-buttons-row#47]
Great plugin here ! Thanks for all the work.
I've got a question on the following part of the code 
`.flex-box {
        display: flex;
        justify-content: space-evenly;
        align-items: center;
      }
`
The **space-evenly** results in the following display 
![s2](https://user-images.githubusercontent.com/38005255/119433388-79e93e00-bd59-11eb-888c-76ca414ac86e.JPG)

This output is more appropriate for my display.

![s1](https://user-images.githubusercontent.com/38005255/119433422-8ff6fe80-bd59-11eb-8f88-1863ea1e2e4e.JPG)

It can be achieved by  changing css flex box justify-content to space-between
`.flex-box {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
`

Obviously,  I prefer to have a setting in the module that can achieve this without changing the code. Am I missing some setting ? The card code 

```yaml
type: entities
entities:
  - type: 'custom:paper-buttons-row'
    buttons:
      - - light.white_2
      - - light.big_lamp
        - entity: light.big_lamp
          layout: icon
          icon: 'mdi:check-bold'
```

Thanks

**Comment by jcwillox** [comment]
If I interpreted that correctly you need to change the CSS on the buttons container and not the buttons themselves, this is not currently possible, however, you should be able to achieve it using something like `card-mod`.

You should also be able to achieve a similar effect using the `width` or maybe even `margin` property on a button, here's an example.
```yaml
  - type: 'custom:paper-buttons-row'
    buttons:
      - layout: icon|name
        icon: 'mdi:fan'
        name: Fan
        style:
          button:
            width: 100%
          ripple:
            display: none
          text:
            padding-left: 21px
      - icon: 'mdi:chevron-down'
      - icon: 'mdi:chevron-up'
```

I was thinking of adding an option to set the styles on the buttons container but decided against adding it, I'm pretty sure it was because the buttons are in their own shadow roots and so the styling wouldn't work properly for some things.
