### ISSUE TITLE
Options variable for the whole row and not just per button

### ISSUE THREAD

**Issue by dimmanramone** [jcwillox/lovelace-paper-buttons-row#5]
Right now it is possible to have options like state and text color per button configuration.
Is it possible to make this global for all the button instead? Something like:

```
          - type: custom:paper-buttons-row
            align_icons: bottom
            state_text:
                  "Online": "Online"
                  "Offline": "Offline"
            state_styles:
                  "Offline":
                    button:
                      color: red
            buttons:
              - entity: sensor.pc
              - entity: sensor.laptop
```
