### ISSUE TITLE
Add image style options

### ISSUE THREAD

**Issue by davidrustingha** [jcwillox/lovelace-paper-buttons-row#50]
I was trying a few different things with the buttons. Since there is no Disney+ icon I created my own and added it via the 'image' option. But the problem I cant figure out how the image could be resised etc. 

Would it be possible to implement this? Or could you give me a pointer on how to achieve this via css? I've tried all possible combinations while inspecting the element in Chrome. The options are there, I just cant get them in the right position.

Thanks in advance!

**Comment by jcwillox** [comment]
Sorry for not replying sooner, this has actually always been possible through the `icon` styles option. The easiest way to resize would just be by setting width/height. If you need to offset the image then you can try using margins/padding.

```yaml
- type: custom:paper-buttons-row
  buttons:
    - image: /local/christmas-lights.png
      style:
        icon:
          width: 120px;
          height: auto;
```
