### ISSUE TITLE
Icons and text disappear when device turned 'on'

### ISSUE THREAD

**Issue by spicerackk** [jcwillox/lovelace-paper-buttons-row#54]
Love the card, however whenever I turn a device on (switch or light), it disappears from the card. I can still click it and it will work, but when it's 'on', the entity is gone. 

I am using the noctis theme (https://github.com/aFFekopp/noctis), so not sure if that is an issue or not. 

I'm sure there is a way to control colours for state with your card, but I'm unsure how to implement it properly.

**Comment by jcwillox** [comment]
I'm not sure why that'd be happening I tested with the noctis theme and everything seems to be working. Do you still have the issue when using Home Assistant's default theme? Do you have an example config that has the issue?

**Comment by thijsputman** [comment]
Might be running into the same / a similar issue:

The below results in `Uncaught (in promise) TypeError: e.state.toLowerCase is not a function`.

```yaml
  - name: Some entity
    entity: input_boolean.some_entity
    state: true
    state_styles:
      "on":
        icon:
          color: var(--warning-color)
        name:
          color: var(--warning-color)
```

Removing `state:  true` (which is the default anyway I guess?) resolves the issue...
