### ISSUE TITLE
Ability to evenly space multiple buttons to each other

### ISSUE THREAD

**Issue by alexrmay91** [jcwillox/lovelace-paper-buttons-row#55]
I have a few few buttons of varying widths, so they don't appear centered overall.

![image](https://user-images.githubusercontent.com/67204669/126913022-fa33979c-acff-4cd4-8b07-829d722b2d8e.png)

![image](https://user-images.githubusercontent.com/67204669/127078906-aceb07cd-d4ad-4b73-a263-d4cab55b0df1.png)

Here's an example of a card along with the same card broken into a horizontal stack. You can see the plain paper-buttons card isn't evenly spaced/centered. Then another image of the buttons with a colored background to see what's going on. Downsides of using a horizontal stack are the borders as well as the fact that `base_config` can't be used.

Let me know if I'm missing a way to do this, but some sort of `button spacing` option relative to each other would be great to have. Maybe a `button width` option instead? Something to normalize button widths and give the ability to space them evenly.

Here's the config for the top card:

```
type: entities
entities:
  - type: custom:paper-buttons-row
    base_config:
      style:
        name:
          color: white
          font-size: 16px
        state:
          font-size: 10px
    buttons:
      - entity: binary_sensor.bedroom_door_contact
        layout: name_icon_state
        name: Bedroom Door
        state_icons:
          'off': mdi:door
          'on': mdi:door-open
        state_text:
          'off': Closed
          'on': Open
      - entity: binary_sensor.garage_door_contact
        layout: name_icon_state
        name: Garage Door
        state_icons:
          'off': mdi:garage-variant
          'on': mdi:garage-open-variant
        state_text:
          'off': Closed
          'on': Open
      - entity: input_boolean.bedroom_occupied
        layout: name_icon_state
        name: Bedroom
        tap_action:
          action: more-info
        state_icons:
          'off': mdi:account-outline
          'on': mdi:account-alert
        state_text:
          'off': Empty
          'on': Occupied
```
</div>
