### ISSUE TITLE
Is there a way to control flow/alignment of the buttons?

### ISSUE THREAD

**Issue by nathanmfast** [jcwillox/lovelace-paper-buttons-row#56]
Currently I have a dashboard that looks like this:
![image](https://user-images.githubusercontent.com/5238018/128126785-16bba406-127e-4493-9217-b63c6da385a8.png)

Would like to achieve something like this:
![image](https://user-images.githubusercontent.com/5238018/128126936-8f3b279b-b56f-471d-8a63-90d70bdd7a26.png)

Not every detail is important here, the main thing is being able to control the flow/alignment of buttons to achieve that left alignment so it mixes well with other controls like slider-entity-row and fan-percent-button-row.

Is there a relatively easy way to do this already or would this require a change to the plugin to support?

**Comment by jorgeassuncao** [comment]
Plus one for that!

The control of the flow/alignment would be a very welcomed feature.

**Comment by jcwillox** [comment]
Well, ultimately it comes down to a bit of CSS, in your case, this should be achievable by setting the horizontal margins to `auto` on the middle button. 

The maybe more ideal way would be to set the flex-box for the buttons to `space-between` but you can't currently do that without an external tool like `card-mod`.

```yaml
type: entities
title: Internet
state_color: true
entities:
  - type: custom:paper-buttons-row
    base_config:
      style:
        button:
          background-color: var(--table-row-background-color)
          border: 1px solid
          border-color: '#FFFFFF'
          border-radius: 4px
          justify-content: center
    buttons:
      - icon: mdi:router-wireless
        name: ROUTER
        tap_action:
          action: call-service
          service: shell_command.reboot_router
      - icon: mdi:lan
        name: WAN
        # set horizontal margins to auto
        style:
          button:
            margin-right: auto;
            margin-left: auto;
        tap_action:
          action: call-service
          service: shell_command.restart_wan
      - icon: mdi:wifi
        name: WLAN
        tap_action:
          action: call-service
          service: shell_command.restart_wlan
```

**Comment by nathanmfast** [comment]
You're a rockstar!
Thanks man, just what I needed.
For any onlookers, here's another handy bit of code applying the same principle to get two buttons aligned with the outside edges:

```yaml
      - type: custom:paper-buttons-row
        buttons:
          - entity: light.living_room_couch_lamp
            name: Couch Lamp
            style:
              button:
                margin-right: auto;
          - entity: light.living_room_tv_lamp
            name: TV Lamp
            style:
              button:
                margin-left: auto;
```

It looks like this (in context):
![image](https://user-images.githubusercontent.com/5238018/129128815-c2911e5e-5202-485f-9171-a9f71e8c30b5.png)
