### ISSUE TITLE
Navigate does not work, what am I'm doing wrong?

### ISSUE THREAD

**Issue by dannymertens** [jcwillox/lovelace-paper-buttons-row#6]
Hi,

Want to create a button row menu for my dashboard, so just navigate to a different tab,  LL dashboard, probably something stupid of me, I'm no developer, but get no errors and see the buttons only they dont work when I click on them? :-(

![image](https://user-images.githubusercontent.com/46963011/78450855-dedb6380-7681-11ea-9b7e-3160e8fb74c0.png)

```
type: entities
entities:
  - type: 'custom:paper-buttons-row'
    buttons:
      - action: navigate
        navigation_path: /lovelace-iphone/home
        icon: 'mdi:home'
      - action: navigate
        navigation_path: /lovelace-iphone/beveiliging
        icon: 'mdi:alarm-light'
      - action: navigate
        navigation_path: /lovelace-iphone/verlichting
        icon: 'mdi:ceiling-light'
      - action: navigate
        navigation_path: /lovelace-iphone/calendar
        icon: 'mdi:calendar-month'
      - action: navigate
        navigation_path: /lovelace-iphone/camera
        icon: 'mdi:webcam'
```

**Comment by jcwillox** [comment]
Have a look at the examples in the docs you are not defining an action correctly.

You need to specify what type of action want you most likely want to use `tap_action`.

This is how the action should be defined.
```yaml
icon: 'mdi:home'
tap_action:
  action: navigate
  navigation_path: /lovelace/...
```

**Comment by dannymertens** [comment]
Hi,

My apologies I probably had the mention that also, this what I thought also before so tried this already but also does not work :-(

Kind regards,
Met vriendelijke groet,

Danny Mertens

**Comment by jcwillox** [comment]
Well, the example below works perfectly for me. Try to make sure the URLs are correct and that your configuration is correct.

```yaml
type: entities
entities:
  - type: 'custom:paper-buttons-row'
    buttons:
      - name: Navigate
        tap_action:
          action: navigate
          navigation_path: /lovelace-testing/testing-2
```
