### ISSUE TITLE
Extend paper buttons row no longer honoring position on iOS

### ISSUE THREAD

**Issue by gvssr** [jcwillox/lovelace-paper-buttons-row#67]
When using extend_paper_buttons_row to embed a button in an entities row, it now defaults to "right" and can't be set to "center" on the iOS app and mobile Safari:
![image](https://user-images.githubusercontent.com/61377476/145857285-ee14cf60-4495-4fd2-944c-282d0a257d95.jpeg)

While on a desktop browser it does display correctly:
![image](https://user-images.githubusercontent.com/61377476/145856901-7bac9755-2fba-4ddb-9c18-e469826e167d.png)

**Comment by YvesZH** [comment]
+1 Same here

**Comment by jcwillox** [comment]
It seems your using the `position` option wrong, not sure how/if it worked like that before but it should be like this
```yaml
  - entity: input_boolean.test
    extend_paper_buttons_row:
      position: center
      buttons:
        - entity: scene.daylight
          icon: mdi:brightness-5
  - entity: input_boolean.test
    extend_paper_buttons_row:
      position: right
      buttons:
        - entity: scene.daylight
          icon: mdi:brightness-5
```
