### ISSUE TITLE
Add option to fire event on tap

### ISSUE THREAD

**Issue by legomind** [jcwillox/lovelace-paper-buttons-row#7]
Title says it all. I want to fire an event to start a node-red flow.

**Comment by jcwillox** [comment]
Sure I'll look into adding that.
For now, you can use scripts to mimic that behaviour, for example,
```yaml
script:
  fire_my_event:
    sequence:
      - event: MY_EVENT
        event_data_template:
          name: myEvent
          customData: "{{ myCustomVariable }}"
```
and to call it,
```yaml
service: script.fire_my_event
service_data:
  myCustomVariable: "myCustomData"
```
