### ISSUE TITLE
Templating tap_action

### ISSUE THREAD

**Issue by fusionstream** [jcwillox/lovelace-paper-buttons-row#74]
I'm trying to template a tap_action to run different scripts based on the state of an entity

```
      - type: custom:paper-buttons-row
        buttons:
          - entity: input_boolean.ac_fan_dryout_running
            icon: mdi:hair-dryer
            layout: icon|state
            tap_action:
              action: call-service
              service_data: {}
              target: {}
              service: >
                {% if is_state('input_boolean.ac_fan_dryout_running',
                'off') %}
                  script.s_room_ac_fan_dryout_begin
                {% else %}
                  script.s_room_ac_fan_dryout_cancel
                {% endif %}
            state_styles:
              'on':
                color: green
              'off':
                color: red
            state_text:
              'on': Cancel Dryout Sequence
              'off': Begin Dryout Sequence
```

The error I get is "Failed to call service {% if is_state('input_boolean.ac_fan_dryout_running', 'off') %}"

Would this mean this feature is not implemented yet?
