### ISSUE TITLE
[feature] Provide usage of entity unit_of_measurement

### ISSUE THREAD

**Issue by Masterz69** [jcwillox/lovelace-paper-buttons-row#80]
F.e. by adding to layout configuration 'units', which will be entity attribute unit_of_measurement, prefixed with space symbol.

**Comment by jcwillox** [comment]
For the time being, you can manually add units using a simple template, or even automatically using Jinja2 templates.
```yaml
- entity: sensor.top_fuel_station
  layout: state
  state:
    postfix: " ¢/L"
```

**Comment by Masterz69** [comment]
Tried to use template in `postfix` - it not working, imho.

``` yaml
                    - entity: sensor.sns_boiler_out
                      layout: state
                      state:
                        postfix: "{{ state_attr('sensor.sns_boiler_out', 'unit_of_measurement') }}"
```
produce 
![image](https://user-images.githubusercontent.com/15225823/150642061-72cdcc77-1600-43ee-8270-39cb50175a88.png)
