### ISSUE TITLE
alarm_control_panel icon color not following entity states

### ISSUE THREAD

**Issue by Masterz69** [jcwillox/lovelace-paper-buttons-row#81]
As for now, v.1.0.0., see it always in same color, regardless of Armed/Disarmed state.
Would be nice to have icon color followed alarm control panel state.

![image](https://user-images.githubusercontent.com/15225823/150398724-f8e60d27-5253-43ec-8796-c80b23da9897.png)

**Comment by jcwillox** [comment]
I could make it respond to the inactive/active states but then it'd show up yellow when "active", paper-buttons doesn't currently extract the colour from the entity, that is a future goal.

You just set those colors yourself using `state_styles`

```yaml
state_styles:
  armed:
    icon:
      color: red
  disarmed:
    icon:
      color: green
```

**Comment by Masterz69** [comment]
Actually there is more armed% states (like armed_away, armed_night, ...).
As well as `arming` and `triggered`.... 

So, see nice feature: in `state_styles` to have `default` style - for others, not named in list states.
To be like
```
state_styles:
  disarmed:
    icon:
      color: green
  arming:
    icon:
    color: yellow
  default:
    icon:
      color: red
```

**Comment by Masterz69** [comment]
My workaround for alarm panel right now:
``` yaml
entity: alarm_control_panel.shed
icon: 'mdi:shield-lock-outline'
styles:
  icon:
    color: var(--state-off-color)
state_styles:
  disarmed:
    icon:
      color: var(--state-on-color)
  arming:
    icon:
      color: var(--warning-color)
      animation: blink 1s ease infinite
  pending:
    icon:
      color: var(--warning-color)
      animation: blink 1s ease infinite
  triggered:
    icon:
      color: red
      animation: blink 1s ease infinite
```

But would be nice to have no such a piece of config in every place of lovelace.
