### ISSUE TITLE
Texts color - to use --primary-text-color instead of dark blue

### ISSUE THREAD

**Issue by Masterz69** [jcwillox/lovelace-paper-buttons-row#82]
I'm really like consistent in colors & other elements User Interfaces.
As far I see - most of cards using --primary-text-color for texts (names & states): in badges, entity cards, ...

So, there is no big effort, but putting same lines in every paper-buttons-row card is little bit annoying for me :)

```yaml
base_config:
  styles:
    name:
      color: var(--primary-text-color)
```

Otherwise icon names and states are displayed in dark blue. 

Is it possible to align these colors to existing commonly used color scheme ?
Or may be to have some `global config` to have possibility to set a color for `name` for all cards in all lovelaces ?
