### ISSUE TITLE
Postfix not applied when state is template

### ISSUE THREAD

**Issue by Masterz69** [jcwillox/lovelace-paper-buttons-row#83]
Do I right to expect to have postfix added in both cases ?
``` yaml
- type: custom:paper-buttons-row
  base_config:
    name: false
    state:
      postfix: " W"
  buttons:
    - - entity: sensor.sva_lights_power
        icon: 'mdi:lightbulb-group-outline'
        layout: icon|state_name
        name: 'Lights'
      - entity: sensor.sva_lights_power
        icon: 'mdi:lightbulb-group-outline'
        layout: icon|state_name
        name: 'Lights'
        state: "{{ states(config.entity) | round }}"
```

Actually show:
![image](https://user-images.githubusercontent.com/15225823/151536011-17cde1f5-eb32-447e-bf6b-e78cff3c4a72.png)
