### ISSUE TITLE
Radial bar scale doesn't follow min/max value

### ISSUE THREAD

**Issue by MikeTheCleric** [jcwillox/lovelace-paper-buttons-row#89]
Hi! I tried to use the radial bar function to represent a Watt sensor. I set min/max value like the docs but this is I obtained. The screen "01" is the result, the screen "02" is a gauge I used before with the same sensor in it

**This is the result of the chart:**
![01](https://user-images.githubusercontent.com/52752310/167893277-484434d4-d3cf-473b-93e5-dd82389350a1.PNG)

**This one is a gauge with the same sensor in it:**
![02](https://user-images.githubusercontent.com/52752310/167893321-a95731fb-55ee-41fc-8157-3b5d0185e3d6.PNG)

This is the config I use:
```
- type: custom:apexcharts-card
   cache: false
   layout: minimal
   chart_type: radialBar
   yaxis:
     - min: 0
       max: 3000
   graph_span: 2s
   stacked: false
   show:
     last_updated: false
   series:
     - entity: sensor.home_energy_meter_gen5_electric_consumed_w
       name: W
       type: line
       unit: W
       color: "#75ecff"
       show:
         legend_value: false
```

There's something I miss or it's a bug? Thanks in advice.
