### ISSUE TITLE
Base_config entity_id variable?

### ISSUE THREAD

**Issue by erkr** [jcwillox/lovelace-paper-buttons-row#91]
Hi
I found this great button row project where a base config can be specified. Exactly what I need, as I want to define tap actions for all buttons. 
Maybe I'm missing something, but how to specify the entity ID of the button pressed in the base config. I have this working:
```
entities:
  - type: custom:paper-buttons-row
    base_config:
      tap_action:
        action: call-service
        service: hue.activate_scene
        service_data:
          dynamic: false
        target:
          entity_id: null
      double_tap_action:
        action: call-service
        service: hue.activate_scene
        service_data:
          speed: 78
          dynamic: true
        target:
          entity_id: null
      hold_action:
        action: more-info
    buttons:
      - entity: scene.serre_relax
        name: relax
        icon: mdi:palette
        tap_action:
          target:
            entity_id: scene.serre_relax
        double_tap_action:
          target:
            entity_id: scene.serre_relax
```
But in this solution I still have to override the entity id for the tap and double tap for every button. 
Is there any way to replace the 'null' in the base config:
```
        target:
          entity_id: null
```
with the entity id of the actual button?
